### ISSUE TITLE
cant transfer coins, please help.

### ISSUE THREAD

**Issue by yatsquall** [Musicoin/desktop#100]
hi, im using v0.7 an i cant transfer my coins
no option on send, can someone please help me, thanks.

**Comment by Varunram** [comment]
Did you create a new wallet? If you're importing an existing one, do you have the json file?

**Comment by yatsquall** [comment]
I start mining mc like a week ago, so I install v0.7 
I don’t see any options to send the coins out of the wallet
I didn’t install v0.8 yet, I been waiting to see if it works fine, I don’t have that much experience obviously, I need help to transfer my coins or if you recommend to install v0.8 and do it them 
I didn’t see the UTC file in v0.7
Please if you can show me what to do, thanks.

**Comment by Varunram** [comment]
Sorry for the late reply, but which OS are you on?

**Comment by yatsquall** [comment]
hi, i have win 10, but in my wallet v0.7 i cant find the utc file, is not there

**Comment by Varunram** [comment]
Didn't notice this thread, but to those who see it in the future, the UTC file should be there at the home directory (which can be found from the wiki)
