### ISSUE TITLE
The address in the wallet was lost,please help

### ISSUE THREAD

**Issue by erinnyes001** [Musicoin/desktop#105]
today when I open the desktop wallet,  nothing in my wallet,  the address disappear.I try to backup with the keystore,but it doesn't work. anything wrong with my wallet or windows? help~help~

**Comment by Varunram** [comment]
Hey, can you checkout the home directory to see if the json file is still there?

**Comment by Sinner61** [comment]
the situation is exactly the same at 100% Is there a way to resolve or with coins you can be trampled?

**Comment by Varunram** [comment]
I don't get what you mean by trampled, could you be a bit more clear?

**Comment by Varunram** [comment]
Closing due to no response, please reopen if needed.
