### ISSUE TITLE
Manage spending from Multiple Wallets

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#108]
Right now, we can't send a tx of value 100MC if I have two wallets with 50 and 60MC each in them. What we should do ideally is to remove the primary and send buttons that are there right now, implement a single send button, which would manage spending by itself (which in turn requires us to manage the coins). We should see as to how we'll manage dust and tx fees, so maybe this is a good time to allow people to set gas manually as well.

**Comment by cryptofuture** [comment]
Multiple spending not a good idea for default. Due to people would ask, where my money came. Might need switch like `intellectual spending`. Or/and we need like lock switch, to be able to lock some accounts from spending. Anyway should be an interesting thing to implement.

**Comment by Varunram** [comment]
@cryptofuture I don't get you? The idea I meant was we could spend from multiple wallets if the balance is insufficient in a given wallet. And we can lock accounts, as you said, to prevent this from happening, that sounds interesting. The goal is that we must be able to abstract the address level stuff as much as possible while still offering people a chance to tinker with them, if needed.

**Comment by cryptofuture** [comment]
This is like several or two transactions from different accounts, it would be hard explain any support like changelly or something like that why you done it.
Also some exchanges have some minimal deposit limits.
So funds could be lost, without actually losing anything if you split transactions.
As example:
Let's say you have 120 music on first account and 5 on second. And minimal deposit is 10 music.
You sending 125 music, so 5 music cames from second, and non deposited on exchange. Now imagine 20 accounts is with less than 10 music. It would be very hard to explain support why you used different addresses. There for some places just will not credit you, like it was your error.

**Comment by cryptofuture** [comment]
Another think is that is with this feature would be easier to lose funds with mistyping amount. Like you type extra zero, and if usually transaction would fail due not enough funds on only one account, here you will have higher chance just to send mistyped amount collected from multiple accounts. So regardless this feature might sounds cool, it could just create more problems, than solve.

**Comment by Varunram** [comment]
Hm, I agree, maybe we can have it as an option? (btw, in the first case, the 5MC and 120 MC act as two inputs and the deposit would be a single output address) Before this however, we must have another password to unlock the account, like parity has. Once we do that, we'll come back to this.

**Comment by Varunram** [comment]
I think we solved this satisfactorily in release 1.0. Closing this for now.
