### ISSUE TITLE
Musicoin Desktop Wallet Logo

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#109]
Echoing the ideas proposed at https://forum.musicoin.org/topic/185/musicoin-desktop-wallet-logo

**Comment by vtombesi** [comment]
still possible to send logos? (the link says the winner logo should have been selected days ago)

**Comment by XhmikosR** [comment]
Ping @dupstudio in case you are interested.

**Comment by Varunram** [comment]
Forgot to update this thread, Jacob Hulmston has been selected as the winner of the competition and his contribution will be used for release-1.0
