### ISSUE TITLE
Balance didn't refresh automatically

### ISSUE THREAD

**Issue by immartian** [Musicoin/desktop#11]
I connect the miner with an external coinbase, which has some balance already.  However, the GUI didn't refresh its balance after a period of time although the account has some changes with txs in other places.

**Comment by phiferd** [comment]
there should be some logs in the Musicoin folder, maybe you can post them.  Also, if you can compare that with the instance of gmc running by using `gmc attach`.  If they don't match, it's definitely an issue with the GUI.

**Comment by immartian** [comment]
From visual compassion, it seems the problem of GUI. 

http://orbiter.musicoin.org/addr/0xc8b33a4593b298bd82f799a9cd249be3c484371e
![image](https://cloud.githubusercontent.com/assets/81030/22869954/369f6af2-f1de-11e6-8005-2dfea11cdc64.png)

while on Orbiter:

![image](https://cloud.githubusercontent.com/assets/81030/22869957/3d874cd6-f1de-11e6-8738-3cc95674ee07.png)

**Comment by phiferd** [comment]
not sure why you say that.  just check with the instance of gmc running on the computer with the wallet app.

**Comment by phiferd** [comment]
do you think this is an issue, or can I close this?

**Comment by Varunram** [comment]
Assuming this was resolved, I'm closing this for the time-being :)

**Comment by karep** [comment]
Hi, I've some issue...not balance coin
![screenshot_1](https://user-images.githubusercontent.com/32011190/30510744-0eccce56-9af4-11e7-8184-20ab7e529a4a.jpg)

**Comment by Varunram** [comment]
@karep The balance doesn't refresh automatically, it requires that the entire blockchain be synced up to the transaction confirmation's block. Your wallet has synced till 125,000 blocks, so you'd have to wait for 860,000 more blocks.

**Comment by karep** [comment]
@Varunram thanks for info, so this is not bugs? Then I can continue mining? When I can reach 860.000 block?
