### ISSUE TITLE
Issue with time sync on Musicoin desktop wallet v0.8

### ISSUE THREAD

**Issue by Jackdak** [Musicoin/desktop#113]
![000](https://user-images.githubusercontent.com/35490446/34987722-1ff48fa0-fab4-11e7-8b34-e8c5e25a41a0.png)
So basically this is what happens when I open the new wallet, can't do anything else, tried going to bios, time can't be changed no option to change it. It's out by milliseconds.

Tried adding peers, wallets, old and new, can't do anything with the wallet.

Has anyone got any solutions?

**Comment by alkoustas** [comment]
Follow the steps mentioned below.
Press Windows key + X and select Command prompt(Admin).
Type each one of the command below and press enter.
net stop w32time
w32tm /unregister
w32tm /register
net start w32time
w32tm /resync
Restart the computer (or don't restart ;) ).

**Comment by Jackdak** [comment]
Thanks for getting back to me, it's still the same. Just took a while longer for the message to be displayed.

**Comment by Varunram** [comment]
@Jackdak The timer is configured to detect very small changes (1 ms) in time config. All functionalities of the wallet should still function, please let me know if it doesn't. A new release with a reduced polling interval can be made if you find it very inconvenient. Would you like us to do that?

**Comment by Jackdak** [comment]
Thanks for getting back to me. There are many people with the same issue. [https://www.reddit.com/r/musicoin/comments/7qq1b7/wallet_keeps_telling_my_my_clock_is_out_of_sync/](url) [https://bitcointalk.org/index.php?topic=1776113.msg28332605#msg28332605](url)
Personally I'm in no hurry as I know you'll get it fixed, as it stands the wallet isn't functioning on any level for me, if it's all to do with the timer, then maybe we could do without the timer.

**Comment by BeamZappa** [comment]
I'm getting the same issue, I'm out of sync by -2.2 milliseconds, I've tried re-syncing with no luck.
Also am unable to connect to any peers, if I enter them manually get this error from the wallet
"Failed to add peer:Error: connect ECONNREFUSED 127.0.0.1:854"

Any aid will be appreciated.

**Comment by Varunram** [comment]
@BeamZappa This might be because another Ethereum wallet could be running on your system, there's another process running on the port or because you do not have the required privileges. Could you check and come back?

**Comment by Jackdak** [comment]
@Varunram Same issue here when trying to add peers. No other wallets are running.

**Comment by Varunram** [comment]
I have fixed this in the most recent release a couple of days back. Please re-open if you continue to face this issue.

**Comment by BeamZappa** [comment]
Hi,
I'm getting the exact same issue as before, minus the I'm out of sync issue, nothing running on both computers I've tried this on.
