### ISSUE TITLE
Clicking on a wallet's EXPLORER in MDW v0.8 does not display correctly.

### ISSUE THREAD

**Issue by ooof** [Musicoin/desktop#115]
Show Inaccessible: orbiter.musicoin.org

![2018-01-17 14-06-28](https://user-images.githubusercontent.com/392785/35028249-0fb1a218-fb90-11e7-8d32-33b069f050b3.png)

**Comment by Varunram** [comment]
Hey, we've updated this in the most recent version (now available at releases), it should work fine now. We're going to make a ppa soon for ubuntu so that you can update right away. Sorry for the inconvenience!
