### ISSUE TITLE
Failed to load default list: Error: connect ECONNREFUSED 127.0.0.1:8545     Always. What's wrong?

### ISSUE THREAD

**Issue by liuqinA11** [Musicoin/desktop#118]
Failed to load default list: Error: connect ECONNREFUSED 127.0.0.1:8545     Always. What's wrong?

**Comment by Varunram** [comment]
Please mention the OS and the Version of the Wallet. Also, try running as administrator and quit all ethereum wallets. If that doesn't work, pease post the debug message here. Thanks!

**Comment by liuqinA11** [comment]
Operating System Properties:
      OS Name                                           Microsoft Windows 7 Ultimate
      OS Language                                       中文(简体，中国)
      OS Installer Language                             中文(简体，中国)
      OS Kernel Type                                    Multiprocessor Free (64-bit)
      OS Version                                        6.1.7601.23915 (Win7 RTM)
      OS Service Pack                                   Service Pack 1
      OS Installation Date                              2017/7/7 星期五
      OS Root                                           C:\windows

    License Information:
      Registered Owner                                  微软用户
      Registered Organization                           微软中国
   
      Product Activation (WPA)                          Not Required

    Current Session:
      Computer Name                                     LENOVO
      User Name                                         Administrator
      Logon Domain                                      LENOVO
      UpTime                                            37856 sec (0 days, 10 hours, 30 min, 56 sec)

    Components Version:
      Common Controls                                   6.16
      Windows Mail                                      6.1.7600.16385 (win7_rtm.090713-1255)
      Windows Media Player                              12.0.7600.16385 (win7_rtm.090713-1255)
      Windows Messenger                                 -
      MSN Messenger                                     -
      Internet Information Services (IIS)               -
      .NET Framework                                    4.6.1590.0 built by: NETFXREL2
      Novell Client                                     -
      DirectX                                           DirectX 11.1
      OpenGL                                            6.1.7600.16385 (win7_rtm.090713-1255)
      ASPI                                              -

    Operating System Features:
      Debug Version                                     No
      DBCS Version                                      Yes
      Domain Controller                                 No
      Security Present                                  No
      Network Present                                   Yes
      Remote Session                                    No
      Safe Mode                                         No
      Slow Processor                                    No
      Terminal Services                                 Yes

**Comment by liuqinA11** [comment]
Musicoin-wallet 8.0

**Comment by Varunram** [comment]
A new release has been uploaded a few days back . Please check and report back as to whether it fixes your issue.
