### ISSUE TITLE
Time is not sync (windows wallet 0.8 can't sync)

### ISSUE THREAD

**Issue by zradeg** [Musicoin/desktop#119]
So, after installing wallet was launched, but about during 1.5 hours I can see only this image: 
![image](https://user-images.githubusercontent.com/30476267/35170121-2253a7ae-fd70-11e7-9697-78151cea6df9.png)
.
I tried to sync time with different servers, but message still appears.
What can i do to fix it?
Windows 7 Ultimate.

**Comment by djmevans** [comment]
The note at the bottom of the first link from Alex Verboon has the following, which worked on my Domain-associated Windows 7 system:


Synchronizing with an Internet time server

You can synchronize your computer clock with an Internet time server. This means that the clock on your computer is updated to match the clock on the time server, which can help ensure that the clock on your computer is accurate. Your clock is typically updated once a week and needs to be connected to the Internet for the synchronization to occur.

If your computer is on a domain, you can't synchronize your clock with an Internet time server.

Open Date and Time by clicking the Start button, clicking Control Panel, clicking Clock, Language, and Region, and then clicking Date and Time.
Click the Internet Time tab, and then click Change settings. If you are prompted for an administrator password or confirmation, type the password or provide confirmation.

Click Automatically synchronize with an Internet time server, select a time server, and then click OK.

**Comment by Varunram** [comment]
Closing this since its been fixed now (if not, please checkout releases for downloading the updated version of the wallet). Else, sit tight and wait for v1.0 (https://github.com/Musicoin/desktop/tree/release-1.0) which is slated to drop in about two weeks.

**Comment by zradeg** [comment]
Thank you for detailed explanation synс time in windows, but I already said, that it's not work. Wallet writes, that time on my system is different from world time by 1.003 second, than after a few seconds value of differences changes to 1.602 second (for example) without any steps to sync. Therefore any actions to sync time  didn't lead to positive result.

**Comment by Varunram** [comment]
If the time difference is greater than 100ms with the network time, the notification will popup (in the earlier release, it was stricter at 1ms. which hw as then changed due to requests). It will popup once every two minutes but that should not affect the sync of the wallet much, except that the process is slower.
