### ISSUE TITLE
Can not run on macos sierra

### ISSUE THREAD

**Issue by cismous** [Musicoin/desktop#12]
Is it support macos sierra 10.12.3?

The error message:
Musicoin-client quit unexpectedly.

**Comment by phiferd** [comment]
Thanks for filing this.

Looks like this is an issue related to nwjs/chromium.  
https://github.com/nwjs/nw.js/issues/5360

We are using 0.17 of nwjs but Sierra isn't supported until 0.18.  I will look into upgrading the client and post to this issue when there is a new build. 

Also, I don't have access to a computer running sierra -- would you be willing to give it a try after I update and post back here?

**Comment by cismous** [comment]
yes, i can do it

**Comment by phiferd** [comment]
https://github.com/Musicoin/desktop/releases/tag/v0.3-wallet-beta

Upgraded to the latest version of nwjs.  Please give it a try and let me know if it works.

**Comment by cismous** [comment]
Congratulation, it works

**Comment by phiferd** [comment]
wow, you're fast.  :)
