### ISSUE TITLE
Maintain a smaller copy of the chain

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#120]
The way it works right now is that the wallet spins up the `go-musicoin` node, which in turn downloads the entire chain (~40GB now). This might not be needed for people who are simply looking to download the wallet and send some fund from it. Instead, we must do something like what parity does, download a smaller copy of the chain and then validate form there (Parity takes around 5GB now)

**Comment by cryptofuture** [comment]
Just to be clear on subject. Chain takes around 8GB now (with fast), might be even less, I just restarted client several times during development.

**Comment by Varunram** [comment]
Oops, I synced with the wrong branch. My bad. Closing this.
