### ISSUE TITLE
Store user credentials on login

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#122]
Branch: release-1.0
Right now, when we click "Play Music" we are always redirected to the sign up page, regardless of whether we've logged in or not. It would be nice to have persistent storage of sessions, possibly even something like "Welcome, xyz" on the wallet page, if the user is logged in to the website (might require some APIs on the website, so let us know if you plan to take it up).

**Comment by vtombesi** [comment]
This is usually achievable through the use of an access token. Each time a user logs in in a client, the client gets an access token back with user data. The access token is then attached to headers for ALL API call involving authentication. When the access token expires, the client can request a new one - with no additional bother for the user. This could make "Play music" skip login (client could fetch user by access token). Clearly this change should be supported by server, is there already some sort of access token management on the server?

**Comment by Varunram** [comment]
Right, there is access token management and we can save the stuff as mentioned by you but the problem is that the app is opened as an external shell, so we'd need to interface with it somehow, get the token and then hash the password and store it on the local system.

**Comment by Varunram** [comment]
Let's tackle this later since we have other stuff at hand.
