### ISSUE TITLE
Binary size / startup time

### ISSUE THREAD

**Issue by XhmikosR** [Musicoin/desktop#126]
So, looking into the latest release, one can see it's **~430MB for v0.8** versus **~180MB for v0.7**.

What happened there? Is there any way to reduce the size?

**Comment by XhmikosR** [comment]
A few things I can say for sure so far are:

1. The images aren't compressed; this should save more than **~15MB**. PR coming for this.
2. Some of the binary files like gmc.exe has debug info; stripping (Running `x86_64-w64-mingw32-strip.exe gmc.exe`, it goes from **20.5MB** to **18.4MB**. **Everything should be stripped for release builds, IMHO.**

**Comment by XhmikosR** [comment]
Also, note that the huge size leads to slow startup times even on an M2 SSD. Ideally, the files shouldn't pack into one huge file, because it takes a lot of time to unpack it on startup.

**Comment by Varunram** [comment]
Yeah, we noticed the increase in size and it was due to a bug in nwjs-builder which caused different versions of it to have different sizes. However with the new release (https://github.com/Musicoin/desktop/tree/release-1.0), we're using web2exe which shouldn't have these problems (and the problems with various distros).

**Comment by XhmikosR** [comment]
Reading web2exe's README.md it seems it's no longer maintained. Maybe you should look into using something else? Also, do you have any size results of using web2exe?

**Comment by Varunram** [comment]
Yeah, sadly web2exe is not being maintained, but looks to accomplish the thing we expect. I will keep an eye out for other scripts for release-1.0 though. Size results wise, with the macOS wallet, the nwjs release right now is around 440MB, whereas the web2exe one clocks at somewhere around 360MB. Wallet v0. was built on nwjs v0.17.3 and I guess that somehow factors in the build size (although it shouldn't?)

**Comment by XhmikosR** [comment]
For Windows I noticed that the zip file includes 3 separate packages so this takes down the size to 1/3 of what it was assuming you will split the huge zip file.

Definitely an improvement, but yeah, better try to find an alternative solution which is maintained.

**Comment by Varunram** [comment]
Yeah, I'll ask the maintainer to split them. The author of web2exe actually wants a volunteer to maintain that repo, could also do that if alternatives aren't there :)

**Comment by XhmikosR** [comment]
Ah, I already have so many projects that I contribute to :)

But yeah, that, or an alternative in the long term.

**Comment by Varunram** [comment]
Reduced macOS zip size to 114MB (x4 decrease). Should look into linux.

**Comment by XhmikosR** [comment]
@Varunram: unrelated, but how about releasing a hotfix and merging the related code changes to master? The time sync error and the gmc one are pretty important.

**Comment by Varunram** [comment]
Done, I had an age old commit that had to be rebase. Removed gmc too.

**Comment by XhmikosR** [comment]
Hmmm, you didn't actually merge; you created a new commit in master; this will lead to differences and merge conflicts later...

Regardless, how about cutting a new hotfix release too? Not sure how long v1.0.0 will take and being that the issues are quite important, it just makes sense to have a hotfix out.

**Comment by Varunram** [comment]
Sorry, didn't see the comment earlier. New (release-1.0) builds are available at builder.musicoin.org. I just merged the changes from release-1.0 into master, you can expect an official GitHub release soon :)

**Comment by XhmikosR** [comment]
How about adding tooltips for the new play music etc buttons?

Also have you guys thought about digitally signing the Windows binaries?

PS. Can you go through all the images one more time and see if there are
any more to remove? The number of files for is quite big currently...

On Feb 7, 2018 10:09, "Varunram Ganesh" <notifications@github.com> wrote:

Sorry, didn't see the comment earlier. New (release-1.0) builds are
available at builder.musicoin.org. I just merged the changes from
release-1.0 into master, you can expect an official GitHub release soon :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Musicoin/desktop/issues/126#issuecomment-363688987>,
or mute
the thread

**Comment by Varunram** [comment]
Ah, we'll add tooltips thanks for the suggestion! Regarding digitally signing the Windows binaries, I don't know how to do that, so I'd have to look into that. And images wise, yeah, this is the maximum we can remove I guess, since all the images at `interface/` are used right now :(

**Comment by cryptofuture** [comment]
Solved in 1.0
@Varunram close

**Comment by Varunram** [comment]
Yeah, I guess the sizes are pretty reasonable now. Created another issue for signing too, so I think I'll close this one.
