### ISSUE TITLE
Number of files in chaindata folder

### ISSUE THREAD

**Issue by XhmikosR** [Musicoin/desktop#127]
Currently I have ~2400 x 2.05MB files in my `%APPDATA%\Roaming\Musicoin\gmc\chaindata` folder along with a pretty huge log file which is 10MB.

My question is, can't those separate files be combined to reduce fragmentation? Also, wouldn't be wise to flush the logs periodically?

**Comment by Varunram** [comment]
It is a good concern but unfortunately, given that that's decided by upstream geth (whose compatibility we maintain with go-musicoin), there's little we can do.

**Comment by XhmikosR** [comment]
I see. I wonder if anyone has reported this upstream already. I'm not sure if this could be implemented, or how hard it would be. My guess it's they do it by design to support fast syncing.

**Comment by Varunram** [comment]
Opened an issue at https://github.com/Musicoin/go-musicoin/issues/76 regarding this.

**Comment by cryptofuture** [comment]
Nothing you can do here, beside using BTRFS or ZFS with compression. Through with fast 1.0 number of files is lower. You can also use bigger cache size for gmc.
@Varunram close

**Comment by XhmikosR** [comment]
I don't see why this should be closed. It's an upstream issue, sure, but still an issue.

Also, not everyone is using nix; there's Windows also which greatly suffers from this issue.

**Comment by cryptofuture** [comment]
@XhmikosR Is not related to musicoin wallet, and nothing we can't do here at the moment. So this issue is just offtopic.

**Comment by XhmikosR** [comment]
It's not off-topic. It is related to your wallet.

But screw it, why bother.
