### ISSUE TITLE
Connect client to a mining pool

### ISSUE THREAD

**Issue by phiferd** [Musicoin/desktop#13]
Mining without a pool will be difficult, especially for CPU miners.  There is at least one pool setup already, and probably more will follow.  

It would be nice if the client supported the user in getting connected to a pool (optionally).  Ideally, the user would not have to run any commands on the command line, or configure any files.  I'm thinking maybe a button next to the mining toggle that says "Configure..." or something, where you can paste in the address of a pool.  The coinbase should be set to whatever the client coinbase is.

This will require including additional dependencies (such as ethminer and ethproxy), and starting/stopping them by making calls from the app.

**Comment by immartian** [comment]
We better leave it for user to customize by providing a list for their choice, and/or editable.

**Comment by Varunram** [comment]
Let's close this since its not on our list of most recent changes (for now).
