### ISSUE TITLE
[Windows] Won't connect 127.0.0.1:8545

### ISSUE THREAD

**Issue by crossmr** [Musicoin/desktop#130]
Yes, I have the absolute latest version.I only downloaded this last night, so this is any issue with the latest version:

Windows 10 home 64 bit version. 

I downloaded, unpacked, tried to run it. It doesn't find any peers. When I try to manually add peers it kicks out the can't connect error. I tried adding a bunch of the peers from the list, nothing works.  I've permitted the program both directions through the firewall. It seems to be trying to a local host process. Is that being blocked somehow?

**Comment by prrayko** [comment]
Same Issue !!!

**Comment by XhmikosR** [comment]
Run this before running the GUI:

```
Musicoin-wallet-win-x64\bin\gmc\gmc.exe --rpc --rpcapi="db,eth,net,web3,personal" --rpcport "8545" --rpcaddr "127.0.0.1" --rpccorsdomain "localhost" --fast --cache=1024
```

**Comment by XhmikosR** [comment]
Outside the wallet folder. Or inside, whatever, just adapt the command.

**Comment by Seleds** [comment]
I’m not exactly sure how to do that in windows 10...

**Comment by XhmikosR** [comment]
All right, then I guess just wait until @Varunram fixes the issue.

@Varunram: check out the config.std.js; the executable on Windows is **.exe** and spawn doesn't call it right with the current solution. You could try cross-spawn or something, or just do it yourself. But currently, as you can see from the number of issues, the wallet is completely broken, at least for Windows users, and maybe macOS ones.

**Comment by XhmikosR** [comment]
@Varunram: actually, you added back the nix binary in 0,8 while it was removed in https://github.com/Musicoin/desktop/commit/7458591ff64c6baa478dc6c787b0ef0d1fce52e0#diff-f25b731a393be5cf2d79139d75f4b5e6 for this reason.

**Comment by crossmr** [comment]
XhmikosR that did it. Now it's syncing. Now I have to try to move the chain data to another drive

**Comment by Varunram** [comment]
@XhmikosR thanks a lot! Now it makes sense why gmc won't spin up. I'll update the windows packages with the compresses images and everything. (The nix binary doesn't exist in the windows build I think, but I'll check it when I rebuild the stuff. Thanks!)

**Comment by Varunram** [comment]
To all those following this thread: i have updated the packages and they have been back tested back to Win XP and 7. Thanks for the responses :)

**Comment by XhmikosR** [comment]
@Varunram: please update the code. I don't feel confident getting  a binary without the source changes and from an outside link...

**Comment by XhmikosR** [comment]
Oh, and ideally release it as 0.8.1 or something.

**Comment by Varunram** [comment]
@XhmikosR In the end it wasn't a problem with the code itself, it was with `go-musicoin` 2.5.3 which didn't work on Windows. That's why the code itself is unchanged, but the binary is. You can always verify the SHA-sum to make sure that nothing malicious is happening.

**Comment by XhmikosR** [comment]
But go-musicoin is bundled with the wallet, isn't it? And this repo still includes the linux binary, right?

**Comment by Varunram** [comment]
The wallet is bundled with go-musicoin, yes, but upstream (2.5.3) seems to have an issue with windows, which I'l take up at the other repo. Regarding linux binary, no, this doesn't have the linux binary, but has four archives (2 for xp, 2 for windows 7+). 

An alternative and easier fix from the windows side would be to replace the bin/gmc/gmc.exe executable with the windows exe from https://github.com/Musicoin/go-musicoin/releases. Hope its clearer now.

**Comment by Fuzzikago** [comment]
Hi,
i am using the v0.5 because this was the only one which runs ans has peers and sync,  but syncing is running very slow (about 2800 blocks a day) at about 7-8 peers.
So i am at about 1.581.000 an have to wait about 100 days more to see the mined coins in my wallet...

any help ??

**Comment by Fuzzikago** [comment]
Hi, now the 0.8 is running. I started the gmc before and if this was at the end of the Blockchain I started the wallet gui. Nice, now the coins are there! But can I close the cmd window now? Or has is to run always when gui is running?

**Comment by cryptofuture** [comment]
@Fuzzikago 
Try wallet 1.0
1. Windows 7 and later - [64 bit](https://builder.musicoin.org/windows-x64.exe), [32bit](https://builder.musicoin.org/windows-x32.exe)
2. macOS - [64 bit](https://builder.musicoin.org/mac-x64.zip)
3. Linux - [64 bit](https://builder.musicoin.org/linux-x64.tar.xz), [32bit](https://builder.musicoin.org/linux-x32.tar.xz)
4. Windows XP and older - [32bit](https://builder.musicoin.org/windows-x32-legacy.exe), [64 bit](https://builder.musicoin.org/windows-x64-legacy.exe)

**Comment by Fuzzikago** [comment]
It‘s running (1.0) perfect since some days ! Thx a lot

**Comment by cryptofuture** [comment]
@Varunram close

**Comment by Varunram** [comment]
Done!
