### ISSUE TITLE
Musicoin-wallet quit unexpectedly.

### ISSUE THREAD

**Issue by Hyabusa64** [Musicoin/desktop#131]
I just installed the new wallet 0.8 and I get this message each time I try to run it.
Used "sudo chown -R <user> Musicoin-wallet-osx-x64/" but each time I get 
"-bash: user: No such file or directory"
this is the message i get after using the sudo command in terminal on the mac. Any help ?

**Comment by vtombesi** [comment]
Probably you specified "user" as the user, you should have used your own username account. 
Try running
```
whoami
```

**Comment by Varunram** [comment]
@Hyabusa64 the command should be `sudo chown -R Hyabusa64 Musicoin-wallet-osx-x64/` if Hyabusa64 is your output from `whoami`

**Comment by Hyabusa64** [comment]
@Varunram what do u mean by "output" and where do I type whoami??

**Comment by Hyabusa64** [comment]
tried all changing name to my username still no luck. Even created the folder "Musicoin-wallet-osx-x64" and placed the downloaded musicoin app inside the folder. The command in terminal seemed to work but still getting errors when i try to open it.
