### ISSUE TITLE
Musicoin Wallet don't display my balance

### ISSUE THREAD

**Issue by Gorglob** [Musicoin/desktop#132]
Hello,

I start mining Musicoin few weeks ago and i wanted to send to an exchange, but when i open the windows desktop wallet, my balance steel at 0. But if i look on the block chain explorer i see the good balance : https://explorer.musicoin.org/account/0x3ffd0486ac74dbf6663cd0ca1722193c4be8d640
![musicoin](https://user-images.githubusercontent.com/35777839/35349249-b1214fae-013a-11e8-86c8-2682c6b5120b.PNG)
![musicoin2](https://user-images.githubusercontent.com/35777839/35349250-b13e1508-013a-11e8-90a2-88119794f905.PNG)

What can i do ?

(I tried many version of the wallet)

**Comment by NM1991** [comment]
@Gorglob I have the same problem :( I checked on explorer.musicoin.org and my balance is correct. I don't understand where is the problem. We hope someone will help us!!

**Comment by NM1991** [comment]
@Gorglob I solved the problem! The fact that it does not show the right balance is given by the fact that it did not download the block related to that payment. you have to wait for it to synchronize up to the transfer block.

**Comment by XhmikosR** [comment]
See https://github.com/Musicoin/desktop/issues/130#issuecomment-360349727

**Comment by Varunram** [comment]
As pointed out, you have to wait for the wallet to finish seeing in order to actually be able to see your balance.
