### ISSUE TITLE
Failed to create account: Error: CONNECTION ERROR: Couldn't connect to node http://localhost:8545.

### ISSUE THREAD

**Issue by Seleds** [Musicoin/desktop#133]
Failed to create account: Error: CONNECTION ERROR: Couldn't connect to node http://localhost:8545.

my wallet its not connecting its not updating,
Windows 10!
Help!

**Comment by XhmikosR** [comment]
See #130

**Comment by Varunram** [comment]
Closing this in favour of #130 (the packages have been updated now). Thanks!
