### ISSUE TITLE
Timeout waiting for NTP response. 

### ISSUE THREAD

**Issue by cod3gen** [Musicoin/desktop#134]
Wallet wont sync, and log says "Timeout waiting for NTP response". Computer clock is correct, and no other ethash wallets are running in background. Any solutions? Win 10 X64

**Comment by XhmikosR** [comment]
See https://github.com/Musicoin/desktop/issues/130#issuecomment-360349727

**Comment by Varunram** [comment]
Timeout waiting for NTP response means that the wallet can't contact the remote ntp servers for time sync, which most likely means that your computer has a poor internet connection. The time-sync feature has nothing to do with sync, the gmc instance will sync even if there is a time difference, just at a very slow rate.

**Comment by Varunram** [comment]
For other issues, please checkout #130 or download the latest packages from http://hda.me/Musicoin-Wallet.zip. Closing this for now in favour fo #130 .
