### ISSUE TITLE
Constant notifications that my computer time is late

### ISSUE THREAD

**Issue by CordialMouse** [Musicoin/desktop#139]
I'm on Windows 10, using the 64-bit version of the v0.8 wallet. 
When the wallet is open, it gives me constant notifications that my computer time is late. I've tried syncing with several different time servers, but it still keeps informing me that my time is ~1.6 milliseconds late. I could see it warranting a notification if the time was significantly different, but for less than 2 milliseconds? Couldn't we build some kind of threshold into it, so that it doesn't bother you when it's only a few ms off?
Also, there is no way to disable the popups, and they come back immediately after being cleared, making it impossible to click anything behind the notifications.
![computer time](https://user-images.githubusercontent.com/35906141/35489956-bd55bb02-0450-11e8-9ac9-8966afbe8a4e.PNG)

Thanks for reading!

Edit: Notifications are continuing to appear, even after the wallet is closed.

**Comment by Varunram** [comment]
Hey, did you download the latest release of the wallet? The attached screenshot is with an earlier version of the wallet after which the notifications were configured for 100ms intervals. Could you download again and let us know? Thanks!

**Comment by CordialMouse** [comment]
Thank you! I just downloaded the latest release, and the notifications have stopped. Yay!
Except now I have a new problem where it stops syncing ~100 blocks from the latest one, and my balance is showing as 0.00. I'm just not having any luck with the new releases lately! Haha.
