### ISSUE TITLE
Use 7zip for packages

### ISSUE THREAD

**Issue by XhmikosR** [Musicoin/desktop#141]
From a quick test here's my results:

```
 77.960.594 Musicoin-Wallet-win7-x64.7z
123.367.303 Musicoin-Wallet-win7-x64.zip
```

So, it's quite a big size decrease.

/CC @Varunram

**Comment by XhmikosR** [comment]
Note that this is with 7zip 16.04 and LZMA2. So play with it and see how it goes.

PS. the scripts for this, should be in the repo so that anyone can replicate everything...

**Comment by cryptofuture** [comment]
We use self extracted (sfx) 7zip for Windows for automated releases now, just 7zip is surely not an option since, may people will be not able to unpack it.

**Comment by XhmikosR** [comment]
Either way, using LZMA as a compression algorithm would offer the aforementioned gains.

**Comment by Varunram** [comment]
Nicely compressed builds now available at builder.musicoin.org. Closing this for now :)
