### ISSUE TITLE
Lost UTC file

### ISSUE THREAD

**Issue by str82dhead** [Musicoin/desktop#145]
Hello guys,
I have lost my backup wallet file due to hard drive fail. Is there a way to access my wallet again?
I have my password for it.

**Comment by Varunram** [comment]
If you have the private key along with your password, then you can recover your wallet. Else, I'm afraid there's nothing you can do.

**Comment by cryptofuture** [comment]
@str82dhead If you still have access to the hard partitions, you can use software like photorec. However you better to work with your drive copy, to insure minimization of the deleted blocks overwriting.
Also, yes you still need to know your password, and find your account/wallet file along many restored files.
As for hardware fail, typically this is just controller fail, so you can use same disk model as a donor. But yes you may need some paid recovery service help in that case, if you can't do it yourself. And it usually helps to launch disk only on limited amount of the time, so you need to be in hurry.
