### ISSUE TITLE
Recovering Musicoin on OS Reinstall

### ISSUE THREAD

**Issue by jjkindt** [Musicoin/desktop#148]
I had the unfortunate situation of needing to reinstall Windows.  I am now trying to recover my cryptocurrencies, in particular, Musicoin.  I have my public key and I know the password that it was created with.  I tried to add and existing account but was unsuccessful.  I created a new account with the same password as before and then tried to add and existing account but that did not work either.  If I have my public key and password, can I regenerate the file that goes in the keystore directory?

Thank you

**Comment by Varunram** [comment]
You need the UTC file / the private key in order to be able to restore your account. I'm afraid you've lost your coins.

**Comment by Varunram** [comment]
Closing this as a dup of #145
