### ISSUE TITLE
Remove duplicate favicons

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#150]
Right now, there are two favicons (one at `interface/` and the other at `/`). We should only have the one at `interface/images/`.

**Comment by cryptofuture** [comment]
Icon at '/' used for builds (builder support only jpg, png and bmp - I think that is windows limitation) and also as icon for notifications. Last one could be changed, but png still might be used as icon if we switch to native notification in the future.
So removing an icon is probably a bad idea. And actually achieves nothing.

**Comment by Varunram** [comment]
Oh, Windows again. Well, yeah, it achieves nothing I guess, but having two files seemed to be sort of a passive nuisance. Closing this then
