### ISSUE TITLE
Wallet don't sync

### ISSUE THREAD

**Issue by comeollas** [Musicoin/desktop#16]
I downloaded wallet 0.3 x64 and start it, wallet all time try to connect to peers, but only one or two try to connect and immediately go to 0 peers and don't sync nothing.

I click for continue and create one wallet, this wallet work correctly?

**Comment by phiferd** [comment]
Yes, the wallet UI should be working.  There current version is run by many people.  Sometimes, it takes time to find peers that it can connect to reliably.  How long did you let it run?

**Comment by comeollas** [comment]
Thnx phiferd, if this version work to ppl i see it's my problem.

My wallet stay without restart wallet 1 hour maybe. (i restarted one or two times and i don0t know certainly how many time i have the wallet opened).

I don't close wallet this night  and see if connect peers with this 8 sleeping hours.

**Comment by phiferd** [comment]
ok.  if it isn't connected in the morning, I can walk you through adding peers manually.

**Comment by comeollas** [comment]
oh, perfect if i have this possibility for add peers :)

**Comment by comeollas** [comment]
Thnx you another time :)

**Comment by comeollas** [comment]
Hi, night passed and nothing 0 peers 0 sync bar.

How can i put in hand peers. 

Tmx for your help :)

**Comment by comeollas** [comment]
18hours and nothing i tried with admin rights and nothing too. 
I see the directory in user - app data - roaming but what file i need to edit for put nodes in (and some nodes ip's).

**Comment by comeollas** [comment]
Done, i put what i make for make it running:

I go to windows command console (cmd) and go to musicon wallet installation directory.

Go to bin/go-musicoin directory and run gmc console for access to gmc console.

Write admin.addPeer("enode://9f5d079dfe426b75238f011d17bb79ac019917c3ebb87b696b04cfeeb406b75aa636b265ec237cdc9115e472799b8ac91dc0b24145596fbe8a7ab35c2d840af5@35.187.221.137:30303")
And make two times more the same with this another nodes.

enode://01389822f45080a202f5429d45975d96eea3be88e1af4686f7d1033345755fda8cc6eb07b3ef64fcd3c376e53a97d4e02170fc1a1f0f430ab41b43edeaedeeb0@35.187.205.215:30303

enode://b6c3369280249b13ee893c551c01dbee33f9cecdfca8b63792b9703632d26ef428819f94d7a0d4d976411e5f81811e1823956debc91b5681e01834b6ba308af4@104.198.124.145:30303


After close console and run musicoin windows wallet in 5 seconds found one peer and started to download immediately).

And all work all my mined musicoins stay here :)

**Comment by phiferd** [comment]
Hey, glad you were able to work through this.  Sorry I wasn't around, but thanks for posting your steps to the issue!
