### ISSUE TITLE
Missing Accts on New Wallet Version 1.0

### ISSUE THREAD

**Issue by ncminer** [Musicoin/desktop#165]
I upgraded from version .8 to version 1.0 and after the wallet synced my accts were in the new wallet.However the balance was incorrect and it was missing all coins that were mined in the last 2 weeks even though it synced all current blocks. I closed the wallet and reopened it and all of my accts are missing(4 total). I'm on a Mac OS 10.13.2  There are no Peer connections now and it doesn't appear that the wallet is running. I opened my old Musicoin wallet and my accts aren't there either. I'm not sure how to delete the old blockchain data to see if that helps though because I can't find it. I do have my UTC keys saved though.

**Comment by ncminer** [comment]
Also my old wallet says:   
Your profile can not be used because it is from a newer version of NW.js.
Some features may be unavailable. Please specify a different profile directory or use a newer version of NW.js.

**Comment by cryptofuture** [comment]
Check that your keystore has accounts. If you see files in the place, all should be ok.
In new wallet select Account - Open Keystore (Ctrl+B) in the menu.
Or check location manually: `Username + /Library/Musicoin/keystore/`

Issue looks like your gmc process didn't closed correctly. Before starting wallet, make sure no any gmc processes running. If you restart wallet too fast, there is the chance, that old gmc process didn't finished yet, there for you wouldn't be able to connect and see accounts.

New wallet use newer version of the NW.js there for downgrade is not easy. But its a bad idea to do it. Usually you see balance only after you are fully synced.

**Comment by ncminer** [comment]
I think you're right, gmc hadn't shut down properly or something but its running now. The accts show up in the wallet now but the ammount is still incorrect and it won't connect to any peers. It keeps trying to connect over and over but keeps dropping them. I checked the log files and get this over and over... 
Musicoin Wallet stderr: WARN [02-15|08:21:01] Ancestor below allowance                 peer=f813df879261a4e9 number=1847556 hash=000000…000000 allowance=1847556
WARN [02-15|08:21:01] Synchronisation failed, dropping peer    peer=f813df879261a4e9 err="retrieved ancestor is invalid"

**Comment by ncminer** [comment]
Whats wierd is that when I first installed the 1.0 version it connected to peers right away and went through the synchronization process 100% but the ammount wasn't correct. So even though it was showing that it had synced it wasn't.

**Comment by ncminer** [comment]
Still won't stay connected to the peers. it find them easily but drops them just as quick as it finds them.
Musicoin Wallet stderr: WARN [02-15|11:04:56] Ancestor below allowance                 peer=efb3592f00243962 number=1847556 hash=000000…000000 allowance=1847556
WARN [02-15|11:04:56] Synchronisation failed, dropping peer    peer=efb3592f00243962 err="retrieved ancestor is invalid"

Musicoin Wallet stderr: WARN [02-15|11:06:20] Ancestor below allowance                 peer=efb3592f00243962 number=1847556 hash=000000…000000 allowance=1847556
WARN [02-15|11:06:20] Synchronisation failed, dropping peer    peer=efb3592f00243962 err="retrieved ancestor is invalid"

**Comment by ncminer** [comment]
Having all kinds of errors....
Uncaught Exception...SyntaxError: Unexpected string in JSON at position 3555
SyntaxError: Unexpected string in JSON at position 3555
    at JSON.parse (<anonymous>)
    at HTMLElement.activePeers (chrome-extension://iakcmlebjlcchobefajeefoajejdaikg/interface/elements/msc-profile-view/msc-profile-view.js:356:26)
    at chrome-extension://iakcmlebjlcchobefajeefoajejdaikg/interface/elements/msc-profile-view/msc-profile-view.js:1043:50
Uncaught Exception...SyntaxError: Unexpected string in JSON at position 3555
SyntaxError: Unexpected string in JSON at position 3555
    at JSON.parse (<anonymous>)
    at HTMLElement.activePeers (chrome-extension://iakcmlebjlcchobefajeefoajejdaikg/interface/elements/msc-profile-view/msc-profile-view.js:356:26)
    at chrome-extension://iakcmlebjlcchobefajeefoajejdaikg/interface/elements/msc-profile-view/msc-profile-view.js:1043:50
Musicoin Wallet stderr: WARN [02-15|11:30:57] Ancestor below allowance                 peer=f813df879261a4e9 number=1847561 hash=000000…000000 allowance=1847561
WARN [02-15|11:30:57] Synchronisation failed, dropping peer    peer=f813df879261a4e9 err="retrieved ancestor is invalid"

Uncaught Exception...SyntaxError: Unexpected string in JSON at position 3555
SyntaxError: Unexpected string in JSON at position 3555
    at JSON.parse (<anonymous>)
    at HTMLElement.activePeers (chrome-extension://iakcmlebjlcchobefajeefoajejdaikg/interface/elements/msc-profile-view/msc-profile-view.js:356:26)
    at chrome-extension://iakcmlebjlcchobefajeefoajejdaikg/interface/elements/msc-profile-view/msc-profile-view.js:1043:50

**Comment by cryptofuture** [comment]
Well yes, you could start over if you remove gmc folder.
It always located at `\AppData\Roaming\Musicoin\gmc` folder under Windows, in `~./musicoin/gmc` under Linux and in `Username/Library/Musicoin/gmc` under macOS.
Would be `Username/Library/Musicoin/gmc` for you. As long as gmc going fast trough rejected node, thats ok. But in case its too much you can try smaller config `Advanced - Restore default nodes list` or rename `bootnodes.json.org` to `bootnodes.json` in ``Username/Library/Musicoin/`

**Comment by ncminer** [comment]
I deleted the gmc folder and reinstalled it. It connected to peers right away now and is syncing the wallet. The accts are there but 0 ballance of course. We'll see if the balance is correct this time at 100% (hopefully)

**Comment by cryptofuture** [comment]
Please upload your `bootnodes.json` file here, seems json is broken for your. Could be some bug with array interaction. After you can replace it with `bootnodes.json` from the distribution located in package.nw folder

**Comment by ncminer** [comment]
Yeah it's syncing now but like I said it synced yesterday but still had an incorrect ballance. I'll let you know if it loads everything correctly this time. Thank you very much for your help on this.

**Comment by Varunram** [comment]
Cool, glad that the original issue is now resolved. Closing this for now.
