### ISSUE TITLE
Musicoin Wallet - Gmc not started synchronization yet

### ISSUE THREAD

**Issue by VERTlG0** [Musicoin/desktop#166]
Just downloaded the 64bit linux tarball, and upon completion of a successful synchronization of the wallet I clicked the Send Funds button, and a notification pops up on my screen:

> Gmc not started synchronization yet

> Send function locked until wallet is in sync. 

> Musicoin-wallet

However, the blockchain is fully sync'd as I am solo-mining it right now as well. I watched the wallet sync reach 100% so I dont think its a wallet sync issue. 

I closed down the wallet and re-opened it three more times and each time the same result occurred with trying to send funds.

**Comment by Varunram** [comment]
@VERTlG0 could you post a screenshot (redact the public keys if you want to, no issues)?

**Comment by cryptofuture** [comment]
>Gmc not started synchronization yet
Those message appears until wallet has no idea about current block (you just started it, and gmc didn't connected to even one stable peer) - not started synchronization
>Send function locked until wallet is in sync.
And those appears if you synced for less than 98%

**Comment by Varunram** [comment]
Any updates reg. this?

**Comment by Varunram** [comment]
Please open a new issue in case you have any further problems.
