### ISSUE TITLE
[Desktop v1.0] Right-side corner navigation bar

### ISSUE THREAD

**Issue by AdrianMastronardi** [Musicoin/desktop#169]
Hi,
I'm attaching a screencast to show how the right-side corner navigation bar buttons are working on Mac OS X. As you can see on the video, the "hand" icon which allows you to click and to the task only appears in a little fraction of the space used by the icon, making it difficult to operate and click. It is more severe on "profile" and "my balance".

You can see the screencast here: https://youtu.be/SRBf35tuhBQ

Regards,
AM

**Comment by Varunram** [comment]
I think maximising the wallet should help things out a bit. Currently, what the wallet does is display a web view of the website, meaning that it is the website's design that e have the icons constricted to a small fraction of the space. I'll pass this on to the design folks. Thanks!

**Comment by cryptofuture** [comment]
Yes, current site posses many issues. And as far as I know team working on new one (on new design).

Sadly, as wallet contributor, I have no access to it. And don't want to hack js inside webview for the site, from the wallet code, as those would only hide design issues, but not really solve anything. 
However @Varunram might have ability to share your video.

**Comment by AdrianMastronardi** [comment]
Maximizing doesn't fix, in fact make it even worse (reducing the click area even more). Let's wait for the new design.

**Comment by Varunram** [comment]
I'll see if I can spin something up for the wallet alone, nice catch!

**Comment by Varunram** [comment]
I think since we updated the header, the thing looks marginally better for now, we'll be updating the website slowly to make it more mobile compatible too, that should solve a few issues.
