### ISSUE TITLE
backup wallet?

### ISSUE THREAD

**Issue by kedebuk** [Musicoin/desktop#17]
how to backup this musicoin  wallet address

**Comment by kyoyadmoon** [comment]
macOS: check `/Users/USERNAME/Library/Musicoin/keystore/` 
windows 10: check `C:\Users\USERNAME\AppData\Roaming\Musicoin\keystore`
backup `UTC--` file
if you want to restore, just put UTC file back to the path

if it helps, welcome to donate
Musicoin: 0x1ed96170af161336760355db3a946ad2da50b283
Eth: 0xCAbd12Aa32174bF30F0eABb4AbE367139FBf6B46

**Comment by Darxan** [comment]
I forgot to turn on the MusiCoin purse. How can I decide this issue?

**Comment by Varunram** [comment]
Um, forgot to turn on as in? Can you be a bit more explicit?

**Comment by xjxzx** [comment]
Can you please provide more specific instructions for how to backup the musicoin desktop wallet key? I am on MacOS. I opened Terminal and typed /Users/USERNAME/Library/Musicoin/keystore/. What I get is: /Users/USERNAME/Library/Musicoin/keystore/: is a directory

**Comment by immartian** [comment]
Please back up all the things under this directory. Your wallet is under the names starting with UTCxxxxx

**Comment by xjxzx** [comment]
Still confused on how to locate my private key. All I see in the desktop wallet is my address. Can you provide step by step instructions on how I can find my private key so I can back it up on paper?

**Comment by immartian** [comment]
keystore is not your private key but a compiled file protected by a password.  You should save the file(s) under /Users/USERNAME/Library/Musicoin/keystore/  to other safe place, and restore if local files corrupted. 
Again the wallet file looks like this:
`UTC--2016-04-17T01-23-45.279405976Z--aaaaab3ad17cd9aca6fd5343a53a513685c7aaaa`

**Comment by Varunram** [comment]
There's a wiki page for taking a backup of your wallet over at https://github.com/Musicoin/desktop/wiki/Backup-your-Wallet. Closing this for now.

**Comment by hurr1cane78** [comment]
hi, I have lost my password to my wallet , I have my keystore and all 
I have lost my password to my wallet , I need help

**Comment by immartian** [comment]
There's no way to recover your wallet without password. The fund is lost, sorry for that.

**Comment by Varunram** [comment]
@hurr1cane78 There is no way to recover your funds if you have lost your password. You could try brute forcing if you remember a part of your password, although that is futile in most cases.

**Comment by str82dhead** [comment]
Hello,
Somehow I've lost the keys from the keystore folder. However I have my public wallet address, and I know my password for it. How can I restore it? As the 8th version wants to specify the backup keys.

**Comment by str82dhead** [comment]
What about if I have my password, but don't have the backup keys?
