### ISSUE TITLE
Account balance does not match blockexplorer

### ISSUE THREAD

**Issue by cipherzzz** [Musicoin/desktop#179]
![image](https://user-images.githubusercontent.com/33289322/36451328-be21de42-165e-11e8-8756-1b8e0a7f3b51.png)

**Comment by Dbz1** [comment]
im having the same issue!!!

**Comment by Varunram** [comment]
Need more info on this, the wallet balance will not match the explorer balance if the chain on the wallet hasn't synced yet

**Comment by Varunram** [comment]
Any updates on this issue?

**Comment by Varunram** [comment]
Closing this for now. Please open another issue if you're facing something like this again.
