### ISSUE TITLE
wallet does not synchronize on Mac 

### ISSUE THREAD

**Issue by Dbz1** [Musicoin/desktop#180]
System: mac os sierra version 10.12.6  

Wallet issue: 

Was running on 0.7 now running on 1.0 I'm having trouble wallet not synchronizing or connecting to peers on Mac.
Please help thank you.

also my wallet balance does not match my block explorer

**Comment by Varunram** [comment]
If the wallet doesn't sync, the balance won't match. Can you try resetting to default bootnodes and see if it helps?

**Comment by Dbz1** [comment]
i did through the wallet right?

**Comment by Varunram** [comment]
Is it better now? Is the wallet done syncing?

**Comment by Dbz1** [comment]
no not syncing

**Comment by etaletai13** [comment]
Was this 1.0.0 built by you, or was it downloaded from Releases? And can we try to find out if others are experiencing this same misbehavior? I'm checking everything I can on this end.

**Comment by Dbz1** [comment]
I still need help i was traveling

**Comment by Varunram** [comment]
Can you take a backup of the blockchain directory and sync from scratch? Please download Wallet v1.0.1 and sync since we've hard forked the time you've been away.

**Comment by Dbz1** [comment]
im not sure if i understand, what blockchain directory ?

**Comment by Dbz1** [comment]
im not sure what happen but 1.0 is syncing !!! will it still work ?

**Comment by Varunram** [comment]
The original issue was solved, hence closing this. Please open another issue in case this still persists, thanks!
