### ISSUE TITLE
How do i import my previous account to 1.0 version?

### ISSUE THREAD

**Issue by harisk7** [Musicoin/desktop#181]
# Go through this before opening an issue

### Issue title must be [Operating System] [Release number] Issue
e.g. [macOS] [1.0] Wallet Doesn't Open
This allows us to filter issues way faster, suggest potential fixes and fix them quickly

### Checklist
1. Mention your Operating system. Without it, we pretty much can't do anything.
2. Attach screenshots, redact your public key if needed.
3. Mention expected behaviour, sometimes, we can't figure out what you mean just from the issue title
4. Please have a proper issue title. "WALLET NOT OPENING!!!" is an example of a bad issue title
5. Fill in the sample template below

For issues with translation, open a Pull Request directly without submitting an issue.

--- ANYTHING ABOVE THIS LINE SHOULD BE DELETED BEFORE SUBMITTING AN ISSUE ---

### Sample Template

Title: [macOS] [1.0] Wallet Doesn't Open

1. Operating System: macOS 10.13.2
2. Screenshots: <attached>
3. Expected behaviour: Wallet should open and sync to the blockchain
4. What Happens: Wallet starts and closes immediately
5. Is any other Ethereum Wallet instance running in the background: No

**Comment by Varunram** [comment]
Open wallet 1.0, click import and then select the location of your keystore files based on your operating system.

**Comment by harisk7** [comment]
When I select import, it gives me four options. I choose the keystore
options. But idk at which folder the keys are stored at

**Comment by Varunram** [comment]
Checkout https://github.com/Musicoin/desktop/wiki/Backup-your-Wallet for the directory options

**Comment by Varunram** [comment]
btw, next time, please edit the issue template before submitting. Thanks!

**Comment by Varunram** [comment]
Closing this for now. Please reopen if needed.

**Comment by harisk7** [comment]
there aint no keys in the directory options. i have been trying to look the file name according to the link you have provided but there aint no file there
