### ISSUE TITLE
Wallet 1.0 do not reflect amounts mined with previous versions

### ISSUE THREAD

**Issue by nop25751** [Musicoin/desktop#183]
![musicoin wallet 1 0 2018-02-23 16-23-31](https://user-images.githubusercontent.com/29581524/36604615-137c2812-18b6-11e8-8c51-420c8cf03c21.jpg)
![musicoin wallet 2018-02-23 16-05-50](https://user-images.githubusercontent.com/29581524/36604059-966d6710-18b4-11e8-90c0-a02b4ddb6c3b.jpg)
![musicoin wallet 2018-02-23 16-13-19](https://user-images.githubusercontent.com/29581524/36604061-968c243e-18b4-11e8-944e-26eb961146bf.jpg)

### Sample Template

Title: [macOS] [1.0] Wallets do not not show total amounts

1. Operating System: macOS 10.13.3
2. Screenshots: <attached>
3. Expected behaviour: Wallet open and sync to the blockchain but do not show or reflect the total amount of mined coins in a previous wallet version.
4. What Happens: Wallet 1.0 starts, syncs completely and show 0 total amount. Created a new wallet mined with client wallet v0.5, made a transfer of 1000 Musicoin from newly created account to older account, the amount confirmed and after a couple of minutes shows in the older account on v0.5 (screenshots attached). After updating to the new wallet 1.0 and waited to all sync up both accounts show up but none of the amounts are there. Any help on this matter would be much appreciated. THANK YOU  
5. Is any other Ethereum Wallet instance running in the background: No

**Comment by Varunram** [comment]
Are you at sync with the latest block on wallet v1.0? The balances will not be reflected until the wallet syncs fully (100% as shown on the wallet UI)

**Comment by cryptofuture** [comment]
@nop25751 What gmc version you running?

**Comment by nop25751** [comment]
![wallets 2018-02-23 19-36-10](https://user-images.githubusercontent.com/29581524/36613259-d5fc8908-18d0-11e8-9a07-e806e6486d8c.jpg)
I'm using the latest version of the wallet (v1.0) on one of my desktop imac and mining on my laptop mac with v.05 since it's the only way I know how to mine it on a mac. Is there any other way I can mine this on mac without using v0.5? I sense that maybe that's the problem here

**Comment by nop25751** [comment]
![musicoin wallet 1 0 2018-02-23 19-40-26](https://user-images.githubusercontent.com/29581524/36613496-93dbb58e-18d1-11e8-85c4-5dd0e90fc62f.jpg)

Got a Last Block connected on the 1.0 wallet 3 minutes ago so I guess it's completely synced

**Comment by nop25751** [comment]
@cryptofuture do not have the new gmc version compiled for mac. Using the one that came with v0.5

**Comment by Varunram** [comment]
@nop25751 We asked info regarding gmc because the version bundled with wallet v0.5 shouldn't be able to sync above  block 1200000 due to the UBI hardfork. I think you may be mining on a fork since the block number is about 1.6 million in the screenshot you posted. Could you check balances on explorer.musicoin.org and confirm whether your coins are there?

**Comment by cryptofuture** [comment]
@nop25751 You used real account addresses on the screenshoots?
I doesn't seems to find first on the explorer.
You could find newer gmc versions [here](https://github.com/Musicoin/go-musicoin/releases).
There was an UBI fork, so I think the thing you mining might be not considered as MUSIC...
As for mining: https://github.com/Musicoin/go-musicoin/wiki/Mining-Pools
Different pools usually have own instructions for it.

**Comment by nop25751** [comment]
@cryptofuture what do you mean by real accounts? When I downloaded v0.5 for the first time I created this account (0x78b472455399bbd66198199d39647d7a47ecb1eb) on the software, waited for it to finish importing the chain and then started mining. I only noticed that my coins, or whatever I'm mining, did not reflect on the account balance only after I installed version 1.0 and simply because none of the other versions worked on my mac (one did not sync and the last one before 1.0 did not open at all) so I continued to use 0.5 normally. Also tried to transfer some funds to my online account (0xa4f12b71c6752b5c1596a432912aa78a4bd2cc67) from the 0.5 with no success.

I opened a new account (0x1b0cb5a83f12d9e0a88533c6f09bd1df23ae4234) on the 0.5 after I realized that the old one was not syncing and mined some whatever this coin is in hopes that It could be some misleading information at some point in the chain or something. And that's when I realized none of it is syncing to 1.0. I can transfer amount from one account into another and vice versa but only on v.05 as none of this is reflected on the blockchain, but my 2 accounts are on the blockchain.

Today I uninstalled both version and reinstall them again, I use the wallet 1.0 on a neutral mac computer and the 0.5 just for mining, that's when I noticed that v0.5 does not completely sync with the blockchain it seems that somehow it stops at block 1.643.733 while v1.0 the blocks go over to 2.031.068 (by the time i'm writing this message).

Could this mean that at some point the transactions and mining I'm doing with 0.5 are not reflecting on the chain because it cannot finish sync? Is there a way or a log to check this out and fix this sync problem? RedCoin had a similar problem with their wallet not syncing to the end and not reflecting transactions on the blockchain and they somehow fix it, unfortunately I'm not an expert on this matter and not much available information circulation for mac users. Maybe there could be a way to unblock the error that stops v0.5 from completely sync and that could fix this problem...

Sending screens of what I'm mentioning here, anyone can help me on this matter would be much appreciated? Could there be a way to force a complete sync of v0.5 to the chain so it can reflect my balance and withdraws? or should I consider this MUSIC or what's the name of this coin is lost?

Thank you all for the time and sorry about all this writing but as you can imagine it's time and money consuming just searching for an answer to try and fix this and recover my coins.

For me what is a bit strange is that I'm mining, with a supposedly recommended software, and now no one can tell me what could have gone wrong and now also rises the question if I'm mining the right coin or the wallets are legit... well I really do not know what to think about all this MUSICoin anymore.

HELP!! HELP!!

P.S: - here are the screens, on v0.5 the wallet completely synced and opened by itself and v1.0 is still syncing while I'm writing this and after a complete reinstall.

![musicoin wallet 2018-02-24 15-17-47](https://user-images.githubusercontent.com/29581524/36632102-f0055ad8-1979-11e8-8627-ec7cf8eb8377.jpg)
![musicoin wallet 1 0 2018-02-24 15-33-45 1](https://user-images.githubusercontent.com/29581524/36632107-f8daee84-1979-11e8-92cd-30f3ebd7b6a8.jpg)

**Comment by cryptofuture** [comment]
>what do you mean by real accounts? 

Sometimes people edit addresses to hide real, as address might be the cold wallet, and they prefer to not connect it with their account on the platform they creating post on.

https://explorer.musicoin.org/account/0x78b472455399bbd66198199d39647d7a47ecb1eb

Send you some MUSIC to test. I'm afraid but looks like you been mining after the UBI fork (block 1200000).

**Comment by nop25751** [comment]
I understand that, but these are really all my 3 real wallets created 2 in 0.5 and the other one is from the online account. 

So does that means that they will never get into my wallet? Thank you for the test you did not have to do that, I've checked and it shows on v1.0, will send it back to you to test that out also.

Again thank you for this as I now know that this is a problem with v0.5.

Is there a way to fix this UBI fork block problem?

PS: photos of the transfer you have made, arrived, thank you. But when I tried to send them back to you got this message. Do I need to have some sort of minimum amount on my wallet to do that? 

![musicoin wallet 1 0 2018-02-24 20-17-07](https://user-images.githubusercontent.com/29581524/36634687-1e4001f2-19a0-11e8-8bb6-b6861416497b.jpg)
![musicoin wallet 1 0 2018-02-24 20-18-33](https://user-images.githubusercontent.com/29581524/36634688-22411a34-19a0-11e8-9b82-832ca3368799.jpg)
![musicoin wallet 1 0 2018-02-24 20-17-07](https://user-images.githubusercontent.com/29581524/36634691-27d46c30-19a0-11e8-8ce2-477369f293f0.jpg)

**Comment by cryptofuture** [comment]
>Is there a way to fix this UBI fork block problem?

This is not a problem. Problem is that you started mining, when 0.7 wallet was already available and UBI fork happened in the network. It was hard to miss UBI - you just need to read MUSIC related news time after time, and don't be afraid to ask stupid question. We have forum for users and musicians : https://forum.musicoin.org/ 
Beside there was signal period, just like for Bitcoin with SegWit so, it really was hard to miss.
Even if you restore your minned funds now, there will be no market for it, since this is purely your own forked coin. And couldn't be considered as MUSIC.

>But when I tried to send them back to you got this message.

gas price is hardcoded to `940000` wei which is `0.00000000000094` MUSIC. So to send 0.01 MUSIC you really need to pay `0.01000000000094` MUSIC

**Comment by Varunram** [comment]
@nop25751 As mentioned earlier in this thread, there was a hardfork at block 1200000 and the compatible version of `go-musicoin` (gmc v2.0) was bundled with Wallet v0.7. Since you continued mining on the stale chain with wallet v0.5 (the chain without the Hardfork), I'm sorry to say that the coins are not $MUSIC and are not worth anything (since there are no miners on the stale chain). You can't transfer these coins anywhere since no exchanges support the stale chain, so there really is nothing you can do with these coins. 

A big giveaway that you're on a wrong chain would be that the difficulty is very low and the very fact that CPU mining is profitable. CPU mining is not worth anything now on the MUSIC chain and that was one of the reason we removed the mining functionality in Wallet v0.7 (the HardFork compatible wallet). That being said, there was enough publicity regarding the Hard Fork and we advertised it on a daily basis on the (then open) Slack channel.

**Comment by nop25751** [comment]
@Varunram Thank you for your understanding and feedback on this, maybe I caught the ship late and did not see all the daily advertised messages you put on the slack channel, maybe this is why it led to a misunderstanding to why does the coins did not appear on the new 1.0 wallet for all those, like me, coming from earlier as 0.5 missed all the information too, that only mean one thing for me is that the project is now yet very clearly and understandable to most of us that wanna take it further and all the problems that happened with support for mac user.

Once again thank you for clearing this out for me and also hope this could help some others in need of this info, it's a pity that all hose mined coins ended up in a limbo but that's how crypto works when mistakes are made and that was my mistake on keep mining this. Maybe the poor info that reaches to new users contributed to this but at least now I know what was the problem. Thank you.

How can I mine, on a mac, this coin using cpu even if it's not as profitable as you say it's not? I would like to, at least, clear it out of my head the wallet syncing problem and be able to mine just a few coins to test my wallets and pay you back the 0.01 for all this trouble. It's the least I can do for this.

Once again thank you for the support, for me you can close this thread.

P.S. - updated the wallet to version 0.7, that I finally manage to run and sync on mac, and the balance now it's the correct one and consistent with v1.0 that is 0.01 (the coin you transfer to my account in order to help solve this mystery). THANK YOU

**Comment by cryptofuture** [comment]
@nop25751 I don't need MUSIC back. Also mostly every poll has instructions how to mine
https://github.com/Musicoin/go-musicoin/wiki/Mining-Pools
For example: http://music.minerpool.net/#/help
And is better to run wallet 1.0, though 0.7 will work too.

**Comment by Varunram** [comment]
@nop25751 Thanks for the suggestions and kind words, I'll ensure this doesn't happen again by having a readme notice along with every release. And regarding mining, CPU mining is not that (energy-wise) profitable, although you can still mine. If you have a GPU however, it is profitable and you can take a look at the links cryptofuture provided to get started.

**Comment by nop25751** [comment]
Thank you both.
