### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#186]
We should combine this with other PRs, if possible
```
Unused dependencies
* bignumber.js
* crypto
* debug
* eth-lightwallet-nwjs
* hooked-web3-provider
* koa
* koa-route
* koa-session
* koa-websocket
* mkdirp
* node-localstorage
* os
* path
* promise-queue
* reverse-line-reader
* serve-favicon
* tmp
Missing dependencies
* nw.gui
* y18n
```
y18n might not to be needed, `nw.gui` might have to check

**Comment by cryptofuture** [comment]
https://github.com/Musicoin/desktop/pull/185/commits/8c9258c8b03824387deb1351216697510916f5d1

**Comment by Varunram** [comment]
Closed via https://github.com/Musicoin/desktop/commit/8c9258c8b03824387deb1351216697510916f5d1
