### ISSUE TITLE
 In explorer my balance fine(~75MC). In wallet(version 1.0) my balance 0.00

### ISSUE THREAD

**Issue by asumarokov** [Musicoin/desktop#190]
1. Operating System: windows 10 Enterprise 2016 LTSB (x64)
2. Screenshots: 
![musicwallet](https://user-images.githubusercontent.com/36985598/36892189-a66989d4-1e0c-11e8-8b58-d8d2d8a4f206.jpg)

3. In explorer my balance fine(~75MC). In wallet(version 1.0) my balance 0.00
4. wallet Sync 99.99%
5. Is any other Ethereum Wallet instance running in the background: No

**Comment by cryptofuture** [comment]
Some bad nodes continued to mine after UBI fork.
See #183 for reference
In case you have still running wallet, please go to directory where you unpacked it and open `package.nw/bin/gmc/` directory. After you need to run `gmc attach` from the terminal (cmd, bash, terminal emulator) and post `admin.peers` output here. I really want block those bad nodes, and those nodes are real pain in the ass for us.

As for your problem you should jump to Musicoin directory and remove gmc folder. 
It always located at `\AppData\Roaming\Musicoin\gmc` folder under Windows, in `~./musicoin/gmc` under Linux and in `Username/Library/Musicoin/gmc` under macOS.
Or you could download nightly version of the wallet at https://builder.musicoin.org and select `Advanced - wipe blockchain data` in menu. Also make surely you going to over 2,000,000 with new sync. Unless please post `admin.peers` output. Also while you still using 1.0 it would be cool if you could attach `bootnodes.json` file from the Musicoin local directory. It might have those bad nodes at the top of list.

**Comment by asumarokov** [comment]
Thanks, deleting the gmc folder helped me. For information: I installed the purse only today, I did not install older versions earlier.
