### ISSUE TITLE
windows 7 64x - music coin wallet - i send some money to my wallet

### ISSUE THREAD

**Issue by protyv** [Musicoin/desktop#197]
![image](https://user-images.githubusercontent.com/37076777/36981176-be1fd2ea-208c-11e8-9c2e-527bebe27172.png)

i have send the money to my wallet can u please do n tutorial" or something because i dont have any money in my wallet after do the transference ;S

idk if i need to w8 a bit or just rage about it.. i have 18 usd

**Comment by protyv** [comment]
64x
´´

**Comment by Varunram** [comment]
Did you send coins from the web wallet to the desktop wallet? If so, please download wallet v1.0 and wait for the chain to sync. Thanks!

**Comment by Varunram** [comment]
Closing this since this thread has been inactive for a while. Please open another issue if you continue to experience problems.
