### ISSUE TITLE
I didn't receive any musicoin to the desktop wallet address 

### ISSUE THREAD

**Issue by casablancaz** [Musicoin/desktop#199]
[Windows 10] [0.5] Mining with musicoin wallet 

Hi! I'm a new miner and using nomnom technologies pool to mine music for 3 days. First tried with myetherwallet address and didn't received any music. Yesterday created a wallet using desktop app they're keep sending my earnings to the different addresses. I mailed them send screenshots about my issue but they didn't replied yet...
I have been mining musicoin for 4 day and my wallet is still empty.
Is there something wrong with the desktop app or I'm missing something?

**Comment by bozidark** [comment]
I have same problem on Mac os

**Comment by Varunram** [comment]
@casablancaz could you post your screenshots here? I'm afraid you can't use Wallet v0.5 to mine since that version of the wallet is deprecated and will no longer be able to sync with the chain.

**Comment by xlnd47** [comment]
@Varunram Do i get a bounty for my dutch translation?

**Comment by casablancaz** [comment]
@varunram thanks for your help my problem is solved when I downloaded the new version of musicoin wallet. Sadly my old earning are gone (;_;)

**Comment by Varunram** [comment]
Closing this since the original issue has been solved.
