### ISSUE TITLE
fail to release new recording work

### ISSUE THREAD

**Issue by musicoj** [Musicoin/desktop#2]
When I try to upload a new work with cover picture and recording mp3, and click "Release Work" button, it went "pending" and show "failed" as below.  No logs in log.txt indicating the reason. 

![image](https://cloud.githubusercontent.com/assets/23398496/20211707/a1ebfbec-a83a-11e6-8057-08ffd3ad6bd9.png)

**Comment by phiferd** [comment]
There is also a log called client.txt in the same directly as log.txt.  Can you post both of those files here?  It may be related to an issue we saw yesterday, where the p2p file sharing system did not start properly.

**Comment by immartian** [comment]
sense it's the issue. Let's wait for a new release to fix as a whole.

**Comment by musicoj** [comment]
log files related to "release failure" 
[client.txt](https://github.com/Musicoin/desktop/files/589135/client.txt)
[log.txt](https://github.com/Musicoin/desktop/files/589134/log.txt)

**Comment by musicoj** [comment]
it seems IPFS is not present, no ideas why

**Comment by phiferd** [comment]
from the logs
```
Found outdated fs-repo, migrations need to be run.
Run migrations now? [y/N] 
```

This is the issue.  when ipfs tried to start, it prompted to start migration of the ipfs database.  The version of ipfs that is bundled with the app is apparently newer than (and incompatible with) the version you install originally.  Start the ipfs version that is bundled with the app, let it run the conversion, and then it should work.  Going forward, we should consider having our own ipfs repository directory inside .musicoin.

**Comment by phiferd** [comment]
Also remove the old version that you have so that you don't accidentally start it again

**Comment by musicoj** [comment]
same issue as #4 , close but keep open watching.
