### ISSUE TITLE
Play music tab disappears on frequent switching

### ISSUE THREAD

**Issue by MJMoonbow** [Musicoin/desktop#209]
When switching between the wallet and the play music tab a couple of times, the wallet suddenly only shows the background. Maximising the wallet window fixes this once, but when you switch  again it shows onyl the bg picture
Wallet 1.0.1 x64
Windows 10 64bit OS
![norefresh](https://user-images.githubusercontent.com/37710761/38018732-0dca29b2-3276-11e8-9d96-2718638336b7.png)

**Comment by MJMoonbow** [comment]
P.s thats on the "Play Music" tab. The wallet tab is displayed proper

**Comment by Varunram** [comment]
Nice catch, thanks for reporting. May I know how quickly you changed the tabs so that I may try to reproduce this?

**Comment by MJMoonbow** [comment]
@ around 80 bpm i think lol
that are 4 clicks in 3 secs

**Comment by Varunram** [comment]
This is definitely a bug, thanks!

**Comment by Varunram** [comment]
I guess this is solved with the recent release where the Play Music tab is static along with the navbar.
