### ISSUE TITLE
Move from npm to yarn

### ISSUE THREAD

**Issue by etaletai13** [Musicoin/desktop#211]
I suggest migrating from npm to yarn. Or, at least give instruction for using yarn should anyone want to in their own hacking.

**Comment by Varunram** [comment]
Yeah sure, I have nothing against this, it would be nice if someone could do that for us. Will add bounty to this.

**Comment by cryptofuture** [comment]
Don't see any benefits in this. Also our build system uses npm.

**Comment by etaletai13** [comment]
@cryptofuture Yarn has a number of benefits, if you care to look. The build system is compatible and easily switched. You'll see, then we'll either do it for real or no. It's got a reason.

**Comment by etaletai13** [comment]
`yarn prepare` is now the only necessary command to build after cloning the repo; merge at will.

**Comment by etaletai13** [comment]
#216 is the fixing patch.

**Comment by Varunram** [comment]
Lets continue the discussion at #224.
