### ISSUE TITLE
Design changes towards release-1.5

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#212]
Its been a while since we upgraded the design, so its now time to move on to the design aspect of the wallet. We're looking for implementing a design (https://www.dropbox.com/s/4jva830c062awd5/MC_wallet_diz_v1.psd.zip?dl=0) with a target for release-1.5. I estimate this should take around 4MVPs (a month), so I'm marking this issue with a bounty of 40k MC to reflect the same.  If it exceeds 4MVPs, we can adjust the bounty accordingly.

Anyone interested can drop a message here (along with your email) to be invited to our slack channel where we can discuss further on ideas and expected outcomes on this. If interested, please claim this issue, since this is a big one and we don't want too many hands on it.

**Comment by movingelectrons** [comment]
I am definitely interested, I can get started as soon as I get the client working (again)

**Comment by movingelectrons** [comment]
I am about %5 complete with this so far, I will push what I have done so far before in a few hours

**Comment by movingelectrons** [comment]
I noticed the menu at the top is not in the .psd, is that to remain the same or is it to go away?

**Comment by Varunram** [comment]
@movingelectrons There is no time constraint on this as of now, so you're f ref to work n it and claim the bounty :) Regarding the top menu bar (I assume you mean the current Account, Markets, Advanced, etc) it is there to stay, the psd file was done by a designer, so he forgot that aspect of it.

**Comment by movingelectrons** [comment]
Here is what I have so far: https://github.com/movingelectrons/interface everything still works as far I can tell, but there is still a lot more to do, I plan on continuing to work on this for a few hours daily until completed.

**Comment by etaletai13** [comment]
@movingelectrons Check out the way the desktop app builds currently. You'll note the ux is coming from github:movingelectrons/interface. It looks nice!

**Comment by movingelectrons** [comment]
ok, good to know, so I should be careful about my commits to master branch here on out

**Comment by Varunram** [comment]
Oh, we can leave them too, no utility in having them against each account. Also would be valuable to present a warning dialogue if one tries to delete his account, saying it will be deleted forever (and that he can't reclaim any lost funds if any on that account).

**Comment by Varunram** [comment]
Bounty claimed in https://github.com/Musicoin/desktop-interface/pull/13
