### ISSUE TITLE
Musicoin wallet 1.0 is not syncing

### ISSUE THREAD

**Issue by casablancaz** [Musicoin/desktop#213]
[Windows 10] [1.0] Wallet is not syncing

Hi guys,
I'm using musicoin desktop wallet 1.0 updated from the last version 2 days ago but I still the have the same problem. Tried to delete Ethash chaindata folder and add peers but it didn't worked. Wallet is not connecting any peers sometimes connect 1 peer but instantly loses the connection. When I check my account on the explorer it shows the real amount of wallet. 
Can somebody help me please?

**Comment by Varunram** [comment]
@casablancaz Are you on version 1.0.1? If so, you'd have to wait for a while to catch peers, this is because in the version of geth we use for the hardfork, peer connection is a bit slow. Could you leave the wallet open for a while and see if it syncs?

**Comment by casablancaz** [comment]
Thank you for your answer. I've waited 1 day long but wallet is still not syncing and not catching peers. What else I can do Varunram?

**Comment by Varunram** [comment]
Closing this due to wallet 1.5 being released about a month back which is deemed to be stable.
