### ISSUE TITLE
Win10 64 (1.0) Wallet Coins Showing in Account Explorer but not in wallet after syncing

### ISSUE THREAD

**Issue by kryptogainz** [Musicoin/desktop#218]
Hello,
   I am using win64 and having an issue with my musicoin wallet 1.0. I started mining and receiving all coins in my wallet without any issue. When my balance reached 534.401847281 MUSIC, the remaining amount which now is about 1168.603410 MUSIC as of writing is not showing up in the wallet but rather in the Account Explorer even though my account is fully synced. Please, I would like to know how to get all the coins into the wallet instead of the Account Explorer, Thank you very much.

![capture 1](https://user-images.githubusercontent.com/37938939/38226130-03133dc0-36c6-11e8-96c9-ee5a659cf7ad.PNG)

![capture2](https://user-images.githubusercontent.com/37938939/38226211-6586a032-36c6-11e8-9210-e2cbc2c89e4e.PNG)

**Comment by andriyandriy** [comment]
в мене такаж проблема  ніхто не відповідає на це

**Comment by kryptogainz** [comment]
My problem got fixed after almost a week now but not sure how it got fixed. Download the new wallet https://github.com/Musicoin/desktop/releases/1.0.1 and just leave the wallet open to sync and hopefully your gets fixed too.
