### ISSUE TITLE
[win10] [1.0] music wallet never gave password or anything and it requires one for transfers

### ISSUE THREAD

**Issue by jorpheusr** [Musicoin/desktop#221]
# Go through this before opening an issue

### Issue title must be [Operating System] [Release number] Issue
e.g. [macOS] [1.0] Wallet Doesn't Open
This allows us to filter issues way faster, suggest potential fixes and fix them quickly

### Checklist
1. Mention your Operating system. Without it, we pretty much can't do anything.
2. Attach screenshots, redact your public key if needed.
3. Mention expected behaviour, sometimes, we can't figure out what you mean just from the issue title
4. Please have a proper issue title. "WALLET NOT OPENING!!!" is an example of a bad issue title
5. Fill in the sample template below

For issues with translation, open a Pull Request directly without submitting an issue.

--- ANYTHING ABOVE THIS LINE SHOULD BE DELETED BEFORE SUBMITTING AN ISSUE ---

### Sample Template

Title: [macOS] [1.0] Wallet Doesn't Open

1. Operating System: macOS 10.13.2
2. Screenshots: <attached>
3. Expected behaviour: Wallet should open and sync to the blockchain
4. What Happens: Wallet starts and closes immediately
5. Is any other Ethereum Wallet instance running in the background: No

**Comment by Varunram** [comment]
@jorpheusr How did you create/import your wallet without a password? Either you went ahead with an empty password or you haven't done the importing stuff properly. Are you sure you did this the right way?

**Comment by jorpheusr** [comment]
I started the app after downloading from github. When it loaded there was
an address already. I created a new wallet as well and no password, seed or
dialogue appeared to create one.

**Comment by Varunram** [comment]
Do you have the UTC file handy?

**Comment by jorpheusr** [comment]
Yes

**Comment by Varunram** [comment]
I think you must have not entered a password. Can you try transferring with an empty password?

**Comment by jorpheusr** [comment]
How can I recover the password from the UTC? I tried leaving it blank
didn't work.

**Comment by Varunram** [comment]
The UTC file should be in your home directory (https://github.com/Musicoin/desktop/wiki/Backup-your-Wallet) or you can click the backup option in the wallet. AFTER taking a backup (ie copying the file to some other place), you can wipe your blockchain directory, open the wallet, import your UTC file and check whether it works. Keep us posted n the progress, thanks!

**Comment by Varunram** [comment]
Closing this since there was no follow up after a couple of months.
