### ISSUE TITLE
Musicoin wallet version 1.0 is flaky at best.  I woke up this morning and it said 14 h since last block.  Then I shut it down and restarted and it has no data now and no connections..  Now it has connections but is doing a full resync in stead of just picking up from last point.

### ISSUE THREAD

**Issue by kryptikjim** [Musicoin/desktop#226]
# Go through this before opening an issue

### Issue title must be [Operating System] [Release number] Issue
e.g. [macOS] [1.0] Wallet Doesn't Open
This allows us to filter issues way faster, suggest potential fixes and fix them quickly

### Checklist
1. Mention your Operating system. Without it, we pretty much can't do anything.
2. Attach screenshots, redact your public key if needed.
3. Mention expected behaviour, sometimes, we can't figure out what you mean just from the issue title
4. Please have a proper issue title. "WALLET NOT OPENING!!!" is an example of a bad issue title
5. Fill in the sample template below

For issues with translation, open a Pull Request directly without submitting an issue.

--- ANYTHING ABOVE THIS LINE SHOULD BE DELETED BEFORE SUBMITTING AN ISSUE ---

### Sample Template

Title: [macOS] [1.0] Wallet Doesn't Open

1. Operating System: macOS 10.13.2
2. Screenshots: <attached>
3. Expected behaviour: Wallet should open and sync to the blockchain
4. What Happens: Wallet starts and closes immediately
5. Is any other Ethereum Wallet instance running in the background: No

**Comment by kryptikjim** [comment]
I am not sure the exact block,  but EVERYTIME I restart it,  it loses sync almost immediately.  I moved out to a secondary drive after the last failure.  Now it does not resync, the entire block chain but still losses it.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by cryptofuture** [comment]
Every time the wallet restarted it would be searching peers from beginning. After it would find workable peer, the sync should continue from the around last saved blocked in slow mode.
The way you could check it to make sure:

- Wipe the blockchain, sync to let's say 98% (and remember block)
- Close the wallet, open process manager and make sure no gmc processes left
- Start wallet again, wait for peer to be found, make sure it continues from the around block it stopped before.

**Comment by Varunram** [comment]
As mentioned earlier in this thread, closing and restarting the wallet only compounds the problem, since the gmc client exits and restarts again. Please follow the steps mentioned above and report back.

**Comment by kryptikjim** [comment]
I completed the steps it picked up at block 2, 852,655 with no problem.  I am monitoring now to see if it keeps the connection alive.
Jim



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------
