### ISSUE TITLE
musicoin.org/connect/email    page confusion

### ISSUE THREAD

**Issue by ooof** [Musicoin/desktop#234]
I am here, both in Firefox and Google Chrome.

Picture:

![2018-04-21 11-10-43](https://user-images.githubusercontent.com/392785/39079888-15a4d158-4556-11e8-8f11-a1a308feb801.png)

**Comment by Varunram** [comment]
I think there are multiple things wrong with this page. I'll look into it, thanks!

**Comment by etaletai13** [comment]
Actually, logging in with social for a musician doesn't seem to work either.

**Comment by ooof** [comment]
It is beautiful!      :)
