### ISSUE TITLE
macOS 10.12.6 Copy and Paste issue

### ISSUE THREAD

**Issue by jzgdev** [Musicoin/desktop#242]
Operating System: macOS 10.12.6
Screenshots: N/A
Expected behaviour: command ⌘ + c should copy highlighted text & command ⌘ + v should paste it
What Happens: No functionality, am able to copy/paste via right click in main desktop client but not in explorer window
Is any other Ethereum Wallet instance running in the background: No

**Comment by etaletai13** [comment]
I've looked into this, and it seems to be a known issue with nwjs in general. I'm looking for ways to work around it now.

**Comment by etaletai13** [comment]
https://github.com/Musicoin/desktop-interface/pull/3 This PR into the interface module fixes this.

**Comment by etaletai13** [comment]
@Varunram

**Comment by Varunram** [comment]
Closed via https://github.com/Musicoin/desktop-interface/commit/2d9b07d14ff57a905b5f59cdefcac275534d7c62
