### ISSUE TITLE
Virus false positive. Please sign your code

### ISSUE THREAD

**Issue by crypto4techs** [Musicoin/desktop#243]
1.0.1 wallet is detected as: VBA32 suspected of JS.Crypted.Heur on VirusTotal.
Please sign your code to help reduce false positives like this.

**Comment by Varunram** [comment]
Hey, thanks for catching this. We have #157 still up, I guess its time to revisit that, thanks for the notice!

**Comment by Varunram** [comment]
Let's track this at  #157 now that it is claimed.
