### ISSUE TITLE
Musicoin client not syncing.

### ISSUE THREAD

**Issue by shibe69** [Musicoin/desktop#25]
The musicoin client for windows 10 is not syncing anymore. I leave it on all day but it does not sync.
The balance in musicoin orbiter is correct, but in the wallet the balance does not appear correctly.
Should I install the client for Windows again? Will I lose the balance if I uninstall and install again? 

Many thanks in advance for your response.

**Comment by immartian** [comment]
pls check slack.musicoin.org , there's new version call testers.

**Comment by Varunram** [comment]
@shibe69 Thanks for the report! You could check out our beta build over at our <a href="slack.musicoin.org"> slack channel </a> if you wanna help test our beta build.

Addressing your current issue however, I have one suggestion - please do check if you've synced your machine's time. Its the most probable cause for errors in Wallets. You could also try to manually add files for <a href="">here </a>. And to answer your question, if you do have a backup of your key, you could very well try installing the client again. But you would have to download all the blocks again, which is not so advisable.

Please do comment if your issues still persist after these fixes.

**Comment by shibe69** [comment]
I synced the machine's time but still not working. I want to try to add manually the peers but  I can't find the "Add peers" button, where is it?
Thanks.

**Comment by Varunram** [comment]
@shibe69 Manually adding enodes is a feature introduced in v0.5, please download the same, sync your wallet and add you key there. Please do make sure you backup the key before attempting to switch over to the new client.

**Comment by shibe69** [comment]
I downloaded the v0.5 version and added the peers but it didn't work. Finally I deleted the contents of the folder "chaindata" and now it seems that if it is being synchronized :)

**Comment by Varunram** [comment]
Ah, happens when some data is corrupted. I'll add that to the readme. Glad you found a fix!

**Comment by robertbuerger** [comment]
Hi there,
I'm having the same problem. I've deleted the chain data, added peers but 0.7 is not even connecting to at least 1 peer. So I've tried 0.5 and its downloading the chain until block 1,547,718. From here it does not move forward. "Last block 6h" but 6 Peers connected.
I've tried this 3 times. Always stopping at block 1,547.718.

I'm looking forward to your help.
Thx
