### ISSUE TITLE
Musician login is broken.

### ISSUE THREAD

**Issue by etaletai13** [Musicoin/desktop#251]
Title: [macOS] [1.5] Social login is broken for musicians, as far as I can tell.

1. Operating System: macOS 10.13.2
2. Screenshots: just a blank window
3. Expected behaviour: should go to the music play and publishing part, and does nothing
4. What Happens: page opens up blank, appears to be remote.

It'd be helpful if others can test for the same and confirm that it is the app and not my system.

**Comment by Varunram** [comment]
Well, we fixed this on the website's side, so I get guess we can close this for now. Regarding releases, I'm not su re if that works properly, but again the tab is to play music and not having a full fledged app for the desktop, so I guess we're okay for now.
