### ISSUE TITLE
Need translation string for "Balance"

### ISSUE THREAD

**Issue by movingelectrons** [Musicoin/desktop#257]
We currently have one for "BALANCE IN" but we are going to need one for just "Balance" as well.  Should be easy enough to do.. but to get it actually _right_ in the many, many languages supported, is not something I am prepared to do.  I will go ahead and make a 'slot' in the code for it and copy over "BALANCE IN" for now.

EDIT:  Might want to hold off on this for a bit (until the v1.5 interface is nearly complete?) because I am finding that we are going to need a few more of these, for MUSIC, BITCOIN, and USD, at least, and there might be more?

**Comment by Varunram** [comment]
Yeah sure, lets just copy over the same translation, don't want to go through updating all translations again, as you said. MUSIC, btc, usd, etc don't need translation afaik, so we can leave them as is. (same goes with balance in music, which might be literally translated)

**Comment by etaletai13** [comment]
A sed or perl regex line will take care of this one, so no worries really

**Comment by Varunram** [comment]
As pointed out correctly, this isn't that big of a concern. We use google translate for smaller translations now that the bounty program for translations is closed.
