### ISSUE TITLE
Porting the app to react

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#258]
The wallet as it stands right now is based off node webkit. While it is a good framework, we are still restricted by what designs we can do in it and what features we can support building on vanilla html and css.

Hence, we're looking for someone to port the app to either electron.js or react.js with the aim of supporting better features and the ability to run contracts locally, upload music locally, among other features.

This would be a big task, in fact, the biggest one offered under any bounty program. I expect it to take a total of 8 weeks to finish the task, from getting started to getting the roc calls ready to the design itself. The design schema will be posted on a separate issue, but it is required that people interested in taking this up work in close tandem with the musicoin team and claim this issue.

Requirements for completing this task:
1. Rewrite the app in React
2. Preserve all existing functionality
3. Adhere to design specifications (will be posted)
4. Add features that would be merged on master before the completion of the task
5. Ask to be assigned to this issue via reply here or via email at `varunram@musicoin.org`

**Comment by etaletai13** [comment]
Oh thank god.

**Comment by etaletai13** [comment]
Can we get another repository with just a readme or something along that lines that we're all going to work from the bottom on? Electron and react are a good idea, and I think electron may win out over time.

**Comment by Varunram** [comment]
I was thinking it'd be better if you started working on personal repos and the point me to the repo when the app is ready so that I can merge it into the org account. I can add a README regarding this over here along with the design stuff in about a week, so I guess this issue would be completely ready a after a week. But the web3 calls are independent of design, so you could take this week to study that stuff so that you're on time for the design .

**Comment by etaletai13** [comment]
I think that sounds like a great idea; it'll probably bring up the opportunity to work out the musicoin config file issue along the way. Study time

**Comment by movingelectrons** [comment]
any recommendations for books/etc on react.js and/or electron.js ?  I would love to do this, but I honestly can't claim that I can even do it because I have very little idea what those two frameworks are even capable of.

**Comment by Varunram** [comment]
Hey, I think the react docs should be enough. There are a couple of tutorials on getting started with react, so I don't think it should be that tough to find something similar. 

Also, updating this to reflect that we'll be finalising on React since react can be packaged into an electron app, which makes it the best fit since I like electron only because of its packaging ability.

**Comment by Varunram** [comment]
Small note on this for people interested: Please don't use languages that compile to javascript, its a pain for multiple reasons and we don't want to deal with moving them if they ever lose support.

**Comment by etaletai13** [comment]
I have begun work (about 40 hours of code ago actually) on the react port of the app. It looks like I'm no longer in the @Musicoin org; but I suppose that won't hinder anything.

**Comment by etaletai13** [comment]
https://github.com/etaletai13/musicoin-electron
For the most part I've been getting things to work in the ways that make porting the rest over very a straight-forward process. 

The tests can be written more easily - hopefully easy enough to convince devs to write tests. 

Documentation, you can use some of the yarn for generating a good starting point; so I'm expecting people take those two responsibilities into their consideration when contributing.

There is also some enforcement of the prettier-standard style. We could easily change that, but the system remains. Along with this; I'm asking that any code contributed follow a declared pattern. Are we using prototypes? Are we using es6? Are we writing modules, or a rambling large main process? Are we using the website's api or purely gmc? Do we use promises? How do we write logs? What format and placement do all of the configuration files have, and why?

These are things to consider defining as we move forward, hopefully with enough coders to need the potential confusion handled ahead of time. Please jump in and play with my own repo for this, but always make a new branch with the name of the contribution, short. EG, "fixup-typos-in-readme-markup" or "fixup-typos-in-readme-text". There will be a set of systems that run before committing that cause things of this sort to be easy and natural. They are not in the repo yet. But they will be when I use them for the first time.

Anyway, enjoy and dig in. I don't mean to write books it's just I'm endlessly long winded. Bless you all. † Your fears be raised up killed and visible to know your own fears are needless, for the fear dies just as easily as us. Beloved, be loved.

**Comment by AlexSwiss** [comment]
Hello, i will like to work on this issue also

**Comment by Varunram** [comment]
sure @AlexSwiss, go ahead. I think the first step would be replicating this wallet as is in react, would that be possible?

**Comment by AlexSwiss** [comment]
yes. by working smart. 😃😃

are there devs working on it already so I join? or this is something I will start from scratch?

**Comment by Varunram** [comment]
None as of now :) You'd have to start the project (get the React skeleton up, do some cool stuff with it) and then I shall join you to make sure we implement the wallet stuff in the right way.

**Comment by movingelectrons** [comment]
ah so ive been replaced.. guess i dont need to work on this now then?

**Comment by movingelectrons** [comment]
> Hey, I think the react docs should be enough. There are a couple of tutorials on getting started with react, so I don't think it should be that tough to find something similar.
> 
> Also, updating this to reflect that we'll be finalising on React since react can be packaged into an electron app, which makes it the best fit since I like electron only because of its packaging ability.

so is it safe to assume that one could just write the react app, and someone else will take care of packaging it with electron?
