### ISSUE TITLE
Add a news section to the wallet

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#259]
Adding a news section to the wallet has been a long desired feature. This should be a section of the wallet which would load info such as artist of the week, Musicoin in the news, etc (the news itself will be fetched from an API). This should ideally be done as a React component, since the wallet will be shifting to React and we want the components to be pluggable. Design spec will be followed up with soon.  I expect this to take 2 MVPs and if interested, contributors can comment below and we'll follow up.

**Comment by movingelectrons** [comment]
I am not familiar with React (looking into it now though) but I'm pretty confident I can handle this.

**Comment by Varunram** [comment]
Cool, all open too you, the idea why its required as a react component is that its easily pluggable into the main wallet when we have that ready.

**Comment by movingelectrons** [comment]
its not clear to me what exactly is required to fulfill this, would one be making the whole thing (api, database that feeds the api, and the view in the wallet?)

**Comment by Varunram** [comment]
https://cryptofuture.github.io/news-website/ is a good example of what needs to be done briefly. You could ideally fork the thing, add an Api and then call those APIs from the wallet. The news app itself would be a single page, so I think github pages should be fine.

**Comment by AlexSwiss** [comment]
i will like to work on this project. i love react!

**Comment by Varunram** [comment]
Sure, I think this would come after we've ported the app to react though, would be nice if we could finish that first :)
