### ISSUE TITLE
Send funds popup doesnt show description, just code string {{echo{

### ISSUE THREAD

**Issue by MJMoonbow** [Musicoin/desktop#267]
Send funds popup doesnt show description, just code string {{echo{
nightly build from the 2. July Windows x64
![wallet send funds](https://user-images.githubusercontent.com/37710761/42418223-ff5135c6-829b-11e8-9e24-8a55b7c2c0a3.png)

**Comment by Varunram** [comment]
Thanks for the report, this was due to bad translation. Will fix and update releases. @cryptofuture

**Comment by Varunram** [comment]
Closed via https://github.com/Musicoin/desktop/pull/268/commits/db95f3227df06621fd92c4b6a8093ae5c72a0a3d
