### ISSUE TITLE
I show at send funds windows in value box {{echo(

### ISSUE THREAD

**Issue by musasimsek** [Musicoin/desktop#273]
When I transfer musicoin another adress I show this screen
![hata](https://user-images.githubusercontent.com/32717955/42660206-238201ba-8633-11e8-89ba-d93034b71027.png)

**Comment by cryptocurrencies** [comment]
1 - From Address 
2 - Recipient
3 - Amount (in musicoins)
4 - Password

**Comment by musasimsek** [comment]
:) I now this @cryptocurrencies but everyone is not a coder

**Comment by Varunram** [comment]
Hey, this was closed in 
https://github.com/Musicoin/desktop/commit/db95f3227df06621fd92c4b6a8093ae5c72a0a3d, please download nightly builds from builder.musicoin.org and you should be good, thanks!
