### ISSUE TITLE
New explorer UI

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#277]
The current <a href="https://github.com/Musicoin/explorer">explorer</a> has a somewhat basic UI and could use a big touchup. Good references would be popular explorers like blockchain.info, bitpay or etherscan. Open to increasing bounty if someone comes up with an entirely new design and chooses to implement that as well.

**Comment by thecluff** [comment]
I just finished working on this basic design, and I'm going to start working on implementing it. Any feedback is appreciated! :) 
![musicoinexplorer](https://user-images.githubusercontent.com/29167186/48396638-f7835c00-e6cf-11e8-9925-483b9dc1f17c.png)

**Comment by Varunram** [comment]
Hey, while this looks good I think we can do a bit better wrt the table's UI. Maybe an alternating band based Ui for the table would look good. Also, would be cool if we could have a new page for all recent blocks and minimise the stats when on the main page. But this is a great start and I'm bumping the bounty up to 30k MUSIC for the time being.

**Comment by Varunram** [comment]
Merging this and #284.
