### ISSUE TITLE
RC 0.6 shows a black screen on windows

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#28]
Reported by Chris, investigating into it. The only stack trace so far is: 
```
process.platform: win32
process.env.APPDATA: C:\Users\CloudMinr\AppData\Roaming
process.env.HOME: undefined
process.platform: win32
process.env.APPDATA: C:\Users\CloudMinr\AppData\Roaming
process.env.HOME: undefined
process.platform: win32
process.env.APPDATA: C:\Users\CloudMinr\AppData\Roaming
process.env.HOME: undefined
```

**Comment by immartian** [comment]
running under Wine in Ubuntu, it returns error 
[backtrace.txt](https://github.com/Musicoin/desktop/files/1227270/backtrace.txt)

**Comment by immartian** [comment]
when checking the log there's a line:
`{process.cwd}/bin/go-musicoin/","command":"./gmc"` which is different from current /bin structure https://github.com/Musicoin/desktop/blob/471cec42e9733090b5e91df40d9ee9a2ba271136/config/config.std.js#L7  

temporarily add a new folder "go-musicoin" as I don't want to change the code this moment. Also for OSX build, I have copied osx gmc into bin folder

**Comment by Varunram** [comment]
Well, no idea what that stack trace means. I'll test the OSX version out and respond on this thread

**Comment by immartian** [comment]
The file permission issue may prevail other issues  https://github.com/nwjs/nw.js/issues/3044

**Comment by immartian** [comment]
Updated the RC candidates at https://drive.google.com/drive/folders/0B-22Cu8ErD7hUEJkSm9VOVBUMkU some users have reported successful running up with Windows edition, yet to confirm more, as well Mac edition.

**Comment by Varunram** [comment]
OSX version problems resolved via https://github.com/Musicoin/desktop/commit/b56ae83ed1e18690f33a3cc44558c5786dbd8bb2
