### ISSUE TITLE
No Peers and  nothing happens

### ISSUE THREAD

**Issue by bckbmath** [Musicoin/desktop#280]
[24787:24787:1026/150106.763903:ERROR:sandbox_linux.cc(380)] InitializeSandbox() called with multiple threads in process gpu-process.
process.platform: linux
process.env.APPDATA: undefined
process.env.HOME: /home/matt
Initializing command: {"name":"Musicoin Wallet","path":"{process.cwd}/bin/gmc/","command":"./gmc","args":["--rpc","--rpcapi=admin,db,eth,net,web3,personal","--rpcport","8545","--rpcaddr","127.0.0.1","--rpccorsdomain","localhost","--fast","--cache=512"],"rpcServer":"http://localhost:8545"}
Initialized command: {"name":"Musicoin Wallet","path":"{process.cwd}/bin/gmc/","command":"./gmc","args":["--rpc","--rpcapi=admin,db,eth,net,web3,personal","--rpcport","8545","--rpcaddr","127.0.0.1","--rpccorsdomain","localhost","--fast","--cache=512"],"rpcServer":"http://localhost:8545","absolutePath":"/home/matt/Desktop/linux-x64/package.nw/bin/gmc/"}
Starting Musicoin Wallet: ./gmc, args: [--rpc,--rpcapi=admin,db,eth,net,web3,personal,--rpcport,8545,--rpcaddr,127.0.0.1,--rpccorsdomain,localhost,--fast,--cache=512], cwd: /home/matt/Desktop/linux-x64/package.nw/bin/gmc/
Started Musicoin Wallet: pid=24840
Musicoin Wallet stdout: Fatal: Error starting protocol stack: listen udp :30303: bind: address already in use

Musicoin Wallet stderr: INFO [10-26|15:01:07] Starting peer-to-peer node               instance=GMC/v2.6.2-beta/linux-amd64/go1.9.4
INFO [10-26|15:01:07] Allocated cache and file handles         database=/home/matt/.musicoin/gmc/chaindata cache=512 handles=1024
INFO [10-26|15:01:07] Initialised chain configuration          config="{ChainID: 7762959 Homestead: 1150000 MCIP3-UBI: 1200001 DAO: 36028797018963967 DAOSupport: false EIP150: 2222222 EIP155: 2222222 EIP158: 2222222 Byzantium: 2222222 Engine: ethash}"
INFO [10-26|15:01:07] Disk storage enabled for ethash caches   dir=/home/matt/.musicoin/gmc/ethash count=3
INFO [10-26|15:01:07] Disk storage enabled for ethash DAGs     dir=/home/matt/.ethash              count=2
INFO [10-26|15:01:07] Initialising Ethereum protocol           versions="[63 62]" network=7762959
INFO [10-26|15:01:07] Loaded most recent local header          number=3449356 hash=7d859b…2d321c td=22199555857707113383
INFO [10-26|15:01:07] Loaded most recent local full block      number=3449356 hash=7d859b…2d321c td=22199555857707113383
INFO [10-26|15:01:07] Loaded most recent local fast block      number=3449356 hash=7d859b…2d321c td=22199555857707113383
INFO [10-26|15:01:07] Loaded local transaction journal         transactions=0 dropped=0
INFO [10-26|15:01:07] Regenerated local transaction journal    transactions=0 accounts=0
WARN [10-26|15:01:07] Blockchain not empty, fast sync disabled 
INFO [10-26|15:01:07] Starting P2P networking 
Fatal: Error starting protocol stack: listen udp :30303: bind: address already in use

Musicoin Wallet: child process exited with code 1
Version 1.5.0

[24759:24759:1026/150107.367706:ERROR:gpu_process_transport_factory.cc(1022)] Lost UI shared context.
{ financialData:
   { attach: [Function: bound ],
     accounts: [Getter/Setter],
     userBalance: [Getter/Setter] },
  attach: [Function: bound ],
  selectedPage: [Getter/Setter],
  hideIntroWindow: [Getter/Setter],
  chainVersion: [Getter/Setter],
  syncStatus: [Getter/Setter],
  userPreferences: { attach: [Function: bound ], username: [Getter/Setter] },
  clientUtils:
   { convertToMusicoinUnits: [Function: convertToMusicoinUnits],
     getLogDir: [Function: getLogDir],
     formatBalance: [Function: formatBalance],
     formatBalanceUsd: [Function: formatBalanceUsd],
     formatBalanceBtc: [Function: formatBalanceBtc] },
  accountModule:
   { createAccount: [Function: createAccount],
     getAccounts: [Function: getAccounts],
     getCoinbase: [Function: getCoinbase],
     getNodeId: [Function: getNodeId],
     getBalance: [Function: getBalance],
     addPeers: [Function: addPeers],
     sendCoins: [Function: sendCoins],
     waitForTransaction: [Function: waitForTransaction] },
  version: [Getter/Setter] }
Uncaught Exception...SyntaxError: Unexpected token u in JSON at position 0
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLElement.webviewSetCookies (chrome-extension://fgmfongdbpiklhadlfednkhicghllckd/interface/elements/msc-profile-view/msc-profile-view.js:483:31)
    at HTMLDocument.<anonymous> (chrome-extension://fgmfongdbpiklhadlfednkhicghllckd/interface/elements/msc-profile-view/msc-profile-view.js:1957:46)
** Message: Remote error from secret service: org.freedesktop.Secret.Error.IsLocked: Cannot create an item in a locked collection
^[c

**Comment by Varunram** [comment]
`Fatal: Error starting protocol stack: listen udp :30303: bind: address already in use` means there's another wallet running on the same port - do you have an Ethereum wallet up and running as well?

**Comment by bckbmath** [comment]
ive checked that the port is open and it is open

**Comment by Varunram** [comment]
Hey, sorry for the late response, what's the status on this? Could you post a log similar to that which you posted last time?

**Comment by Varunram** [comment]
Hey, what's the status on this issue?
