### ISSUE TITLE
Not able to sent my Music coins from Desktop Wallet V1.5 to MyEther Wallet

### ISSUE THREAD

**Issue by nirangale** [Musicoin/desktop#281]
Hi,
I'm trying to sent my music coins from desktop wallet V1.5 to Music address in Myether wallet.
I'm providing the home address, Receiving address, Number of Coins and Password. It looks like it sends the coins but I can't find any transactions or the coins remains there with out any change in desktop wallet.
What's happening? can someone help me with this?

**Comment by Varunram** [comment]
Is the wallet up to sync? Does the wallet show the current balance?

**Comment by nirangale** [comment]
Yes the wallet is synched and it shows the current balance.

**Comment by nirangale** [comment]
I retried this just now again after reinstalling the wallet and it worked like a charm.

**Comment by Varunram** [comment]
Closing this since the issue has now been solved.
