### ISSUE TITLE
New Musicoin explorer

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#284]
## New Explorer Backend + Construction
The musicoin explorer is one of the critical pieces of infrastructure that supports the musicoin blockchain right now. While good in its functional performance as it stands right now we would like to have a few advanced features that would serve interesting stats to the community and help the musicoin team keep track of the overall community quotient as well.

To reward people who are developing towards this end, we would like to propose a bounty program to help those interested contribute a new explorer so that we may use it in production. The new explorer has a list of features that we would like in the wallet and are detailed  below.

1. Have a list of the top 100 Musicoin accounts. This must be expandable to 1000 accounts if needed.
2. Have a recent transactions and recent blocks section on the homepage
3. Have a list of hash rate grouped by mining pool and pool wise classification for blocks mined
4. Faster lookup of addresses and blocks
5. API to serve all the above details
6. Better and more user friendly UI/UX design (maybe could be adopted from #277 if its ready before then). An example is https://ethplorer.io

The following section contains a list of bonus features that are not absolutely necessary, but would be rewarded issue wise if completed:

1. Graphs for all the above details in line with standard block explorers
2. Network diagram of connected nodes
3. Total node count and versioning of nodes

The bounty for the base explorer is 100k MC and the bounty for each bonus issue is 20k MC. Completion rewards will also be rewarded depending on the time it takes for a solution to be complete.

Please ask to be assigned to this issue below in the comments thread.

## New Explorer Design:
New designs for the Musicoin Explorer that are in line with the other elements on the main site are welcome. Designs can be free-flowing, without any restrictions as long as they are inline with the other site elements. Bounty for design will be awarded separately based on acceptance of the design.

**Comment by iworkforthem** [comment]
@thecluff are you working on this?

**Comment by Varunram** [comment]
@iworkforthem colors can follow the gold/black scheme of the musicoin website as is right now, there is no restriction on the fonts and other aspects. Please do comment here in case you need something and I can do that for you, thanks!

**Comment by iworkforthem** [comment]
@Varunram ok, will follow the styles of the musicoin website.

**Comment by iworkforthem** [comment]
@Varunram .. is possible for the explorer to connect to infura.io instead of installing parity.

**Comment by Varunram** [comment]
@iworkforthem The musicoin blockchain is pretty small compared to the Ethereum blockchain :) The entire blockchain is around 40-50GB (depending on the mode you run it in), but you could also run it on fast mode to test locally.

**Comment by iworkforthem** [comment]
@Varunram .. in the explorer/routes/contract.js, there is a reference to solc-bin... 

`var versions = JSON.parse(fs.readFileSync('./utils/solc-bin/bin/list.json')).builds.reverse();`

Need to install https://github.com/ethereum/solc-bin as well?

**Comment by iworkforthem** [comment]
@Varunram ... made a change in explorer/routes/contract.js to set solc-bin/bin/list.json correctly, and in explorer/config.js to set the this.ipcPath correctly in mac. Managed to get the explorer running now.

**Comment by Varunram** [comment]
Glad to hear - as long as you're in sync with the musicoin explorer right now, you should be good.

**Comment by thecluff** [comment]
@iworkforthem I've been working on styling the current explorer, but am having issues with connecting to the blockchain. What changes did you make to those files to get it to run on mac?

**Comment by iworkforthem** [comment]
@thecluff i made the following changes;

1. in the routes/contract.js file, i git clone the solc-bin/list.json & updated the path `var versions = JSON.parse(fs.readFileSync('<LOCAL>/solc-bin/bin/list.json')).builds.reverse();`
2. in the config.js file, i install parity using brew & update the ipcPath `this.ipcPath = "/Users/<USERNAME>/Library/Application Support/io.parity.ethereum/jsonrpc.ipc";`
