### ISSUE TITLE
Please put newer release to download on the Code page (July 3 version has issues)

### ISSUE THREAD

**Issue by justanotherminer** [Musicoin/desktop#286]
Please put a newer release on the front page to download (newer than the July 3 version).
The July 3 version of the Musicoin wallet 1.5 has problems (cannot send MUSIC).
(I am unable to download the exe files on https://builder.muciscoin.org - alternatively, please zip the .exe files there so they can be downloaded)
Thanks

**Comment by Varunram** [comment]
Thanks for notifying us on this, will ask our devops engineer @ehsanhajian to fix.
