### ISSUE TITLE
Wallet Freeze and Settings Save

### ISSUE THREAD

**Issue by jattminer** [Musicoin/desktop#29]
I'm having the issue of the wallet freezing once it's open and looking for peers. About 1 minute in I have to close and reopen and it never fully syncs. Also after I create a new wallet and check box for primary it doesn't save the setting. After restart it goes back to original wallet as primary.

**Comment by immartian** [comment]
which version you are using now?

**Comment by jattminer** [comment]
v0.6RC for Windows

**Comment by Varunram** [comment]
Thanks for the report! We'll fix this in upcoming releases

**Comment by jattminer** [comment]
One other thing I wanted to mention is the wallet opens full screen. I'm not sure if it's intended but just letting you know. Thanks!

**Comment by immartian** [comment]
It can be the issue of RC version, we have new build ready to try, yet to update to repo.

**Comment by immartian** [comment]
Please try version 0.7
