### ISSUE TITLE
Music Wallet” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by bckbmath** [Musicoin/desktop#290]
On MACOSX I get this error

Music Wallet” is damaged and can’t be opened. You should move it to the Trash.

**Comment by immartian** [comment]
what?
can you have a screenshot?

**Comment by bckbmath** [comment]
![Screen Shot 2019-06-06 at 05 53 55](https://user-images.githubusercontent.com/38348564/59003656-877d2480-881f-11e9-9a3d-9e5a0e49db89.png)

**Comment by immartian** [comment]
alright, seems it's a common issue on OSX or similar. http://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/

**Comment by bckbmath** [comment]
xattr -cr fixed it
