### ISSUE TITLE
Unlock account musicoin wallet 1.7

### ISSUE THREAD

**Issue by magmaster40** [Musicoin/desktop#297]
Windows 7x64. I can not transfer coins to another account. When performing an operation, visually nothing happens. Confirm transfer - the window is closed. Coins are not translated. "Show private key" - error invalid password. How to unlock account access?

**Comment by immartian** [comment]
Screenshot? Do you have a password to the account in the operaiton?

**Comment by magmaster40** [comment]
Password recorded but not working

**Comment by magmaster40** [comment]
Obviously recorded the wrong password, which really entered when creating an account. It can be fixed? Found it only now, when I wanted to make a withdrawal of coins.

**Comment by magmaster40** [comment]
![111](https://user-images.githubusercontent.com/53387065/62002108-737fe000-b149-11e9-8f1b-b7b0430a2b2e.jpg)

**Comment by magmaster40** [comment]
Forget about it?

**Comment by immartian** [comment]
where did you create the wallet? the same machine?

**Comment by magmaster40** [comment]
Yes

**Comment by immartian** [comment]
guess either you input the wrong password or the keystore file corrupted.

**Comment by magmaster40** [comment]
I did not remember the password correctly. Is it possible to fix it? Fall storage does not damage

**Comment by immartian** [comment]
nobody can crack your password, otherwise, it's not called cryptocurrency. :)

**Comment by magmaster40** [comment]
fk
