### ISSUE TITLE
can not see the "New Releases" and "Coinboard" buttons

### ISSUE THREAD

**Issue by ooof** [Musicoin/desktop#3]
I can not see the "New Releases" and "Coinboard" buttons.

PS：My system is WIN10 Chinese version.

![default](https://cloud.githubusercontent.com/assets/392785/20213077/a79c2c04-a841-11e6-99bd-23a512545d47.PNG)

**Comment by immartian** [comment]
can you try to run up VPN to try again?

**Comment by phiferd** [comment]
Both issues appear to be related to not being able to contact the musicoin API.  The new releases and coinboard menu items are dynamically populated by calling the server for a list, and the button text in the image above it also populated by the API -- the idea being that the service could have more control over the signup flow.  

You can just try pointing your browser to: http://catalog.musicoin.org/api/page/content?page_id=new-releases

You should see something like this if it's working:

`{"content": [{"result": [{"royalties": null, "balance": "0", "contract_id": "0xa5362bf84598e9a8a444d6b587c9eb3effb5ab8e", "contributors": ["0x008d4c913ca41f1f8d73b43d8fa536da423f1fb4"], "resource_url_https": "https://ipfs.io/ipfs/QmU1qaiHiFy1HKa6d44aRSyp1r7rbeMTAuo8UZF7NF8dsP", "song_name": "Test", "work": {"metadata_url_https": "https://ipfs.io/ipfs/QmY3Ym6e5HozURXyZhN8xLZtpSf76mhae9nCpopRWFXEWR", "artist": "Test", "image_url": "ipfs://QmUs9Z5rT1E9aVKtzHY9FdyuXVPKivhz5UFnuLa1Yh5W2o", "owner_address": "0x008d4c913ca41f1f8d73b43d8fa536da423f1fb4", "work_type": "0", "contract_address": "0xa4062a38babbee199a3924c3fe52077ec018339b", "image_url_https": "https://ipfs.io/ipfs/QmUs9Z5rT1E9aVKtzHY9FdyuXVPKivhz5UFnuLa1Yh5W2o", "title": "Test", "metadata_url": "ipfs://QmY3Ym6e5HozURXyZhN8xLZtpSf76mhae9nCpopRWFXEWR", "datetime": "Nov 11, 2016"}, "total_earned": "0", "artist_name": "Test", "total_tipped": "0", "play_count": 0, "contributor_shares": ["1"], "work_id": "0xa4062a38babbee199a3924c3fe5....`

**Comment by ooof** [comment]
@immartian  Turning VPN on or off is not displayed.

**Comment by ooof** [comment]
@phiferd   

This link can be displayed： http://cat
![Uploading 捕获.PNG…]()
alog.musicoin.org/api/page/content?page_id=new-releases

**Comment by immartian** [comment]
So as I understand, you can't display this result in Chrome, but only in Firefox. I think it's still the problem of firewall.

**Comment by ooof** [comment]
I changed a VPN, Google Chrome is still unable to open http://catalog.musicoin.org/api/page/content?page_id=new-releases

The program can not run.

**Comment by Varunram** [comment]
Closing the issue since we've updated the client since then.
