### ISSUE TITLE
Back up your private keys

### ISSUE THREAD

**Issue by Sang-Som** [Musicoin/desktop#32]
How to do it ?
"However, this is a good opportunity to remind you to back up your private keys!"

**Comment by pkefal** [comment]
You can find the instructions here [How to backup your wallet](https://github.com/Musicoin/desktop/wiki/Backup-your-Wallet)

**Comment by Varunram** [comment]
As @pkefal correctly stated, please checkout the threads mentioned above. In any case, semi auto-backup is coming to the new wallet :) Marking this issue as resolved for now.
