### ISSUE TITLE
cannot create a new account

### ISSUE THREAD

**Issue by hirotop** [Musicoin/desktop#34]
Hi, 

I am using windows 64 version of the wallet. When I try to create a new account it says,

"Failed to create account: Error: Method not found"

My another question is "what is the relationship between Musicoin wallet and ethereum wallet? Musicoin wallet shows all my ethereum wallets. So, I guess I can open a new wallet from ethereum wallet and use it for storing Musicoin. Am I correct?

**Comment by hirotop** [comment]
I am updating the issue. 

The client works well on my windows 10 pc (64bit), not on windows 7 pc. 

Thanks.

**Comment by immartian** [comment]
thanks for reporting back. Close for now.
