### ISSUE TITLE
account balance is not refreshed in windows client

### ISSUE THREAD

**Issue by buzz2017** [Musicoin/desktop#35]
Hi,
I am mining using http://music.minertopia.org using Ethereum address

I can see the payouts but the balance is not refreshed in the windows client

Nothing in the debug.log. 

What am I missing?

**Comment by buzz2017** [comment]
I see the balances now refreshing slowly. I let the wallet running so it can sync and balances appear to be showing up now

**Comment by Varunram** [comment]
The chain does take some time to sync, glad its working fine for you now.
