### ISSUE TITLE
blank screen 2nd time running program

### ISSUE THREAD

**Issue by musicoj** [Musicoin/desktop#4]
on Windows

I closed the program and try to restart it again but this time it displays only blank screen. I restart computer and run again, it backs to normal, but repeat the same issue once I close the program and re-open it by clicking the .exe file. 

[client.txt](https://github.com/Musicoin/desktop/files/589124/client.txt)
[log.txt](https://github.com/Musicoin/desktop/files/589125/log.txt)

**Comment by phiferd** [comment]
Seems likely to be related to #2 .  Again, in the logs:

```
Found outdated fs-repo, migrations need to be run.
Run migrations now? [y/N] 
```
run the included version of ipfs from the command line once and let it upgrade the repo (or just delete the ipfs repo).

**Comment by musicoj** [comment]
it's solved after manually migrated the repo. Issue can be tentatively closed but need future solutions.
