### ISSUE TITLE
SYNC issues persist

### ISSUE THREAD

**Issue by igotfits1** [Musicoin/desktop#41]
seems like my wallet does not sync up anymore, upgraded to .6 same story :(

**Comment by igotfits1** [comment]
I0907 20:30:18.521040 p2p/server.go:313] Starting Server
I0907 20:30:20.407556 p2p/discover/udp.go:217] Listening, enode://82ced8d46d2f38bfdc8djkd78fjg7d4df3bfa8aa81ae1e7ddb7fad947ecacd79b2c4e8b2173f945ac270c10bd88f2462ef6cdc3e28be02f557a1916104b7e4c3@[::]:30303
I0907 20:30:20.407556 p2p/server.go:556] Listening on [::]:30303
I0907 20:30:20.409558 node/node.go:296] IPC endpoint opened: \\.\pipe\geth.ipc

i get this when firing up gmc.exe though powershell

**Comment by Varunram** [comment]
The IPC endpoint is open, which means that there is some other problem (other than gmc) which is the reason that the client is not syncing. Common issues could be a poor internet connection or minuscule time differences. Could you check and report back? @igotfits1

**Comment by igotfits1** [comment]
i was able to get it synced up, i used v6 seems like the list of peers helped out.
i just downloaded version .7, with the version .7 do i need to update client to 2.0 i downloaded the exe do i rename it and put in the bin folder to replace the old gmc.exe?
