### ISSUE TITLE
Issue with osx version v0.7

### ISSUE THREAD

**Issue by ncminer** [Musicoin/desktop#43]
I'm having an issue with the osx v0.7 version that I'm not having with V0.5  All I get is a blacked out wallet.  http://i1064.photobucket.com/albums/u378/NCreefguy1/Screen%20Shot%202017-09-10%20at%208.16.52%20PM_zpshhvilu5m.png

Any ideas?

**Comment by immartian** [comment]
We didn't make full test on OSX due to environment constraints.  Can you provide some log info under /Library/Musicoin/logs ?

**Comment by ncminer** [comment]
Nothing is coming up under /Library/Musicoin/logs.

**Comment by immartian** [comment]
Same log-lessness at your side, @Varunram ?

**Comment by Varunram** [comment]
Yes, I'm not getting any log too.

**Comment by Varunram** [comment]
@ncminer the issue is now resolved and we have updated the release reflecting the same. Could you try downloading the updated wallet and retry?

**Comment by ncminer** [comment]
I downloaded and installed and it is now working now. For some reason however I'm getting an error code when I tried to send a small test transaction from 1 of the 2 accounts that I have listed in the wallet. It says "Failed to send: Error: Unlocking account failed: Error: could not decrypt key with given passphrase"  I know that I'm using the correct password because it worked on the other account.  Could it have something to do with that account being set as an external coinbase? Im just wondering if I did something wrong or did it not install properly.

**Comment by immartian** [comment]
you need to have the keyfile under local keystore folder, then possible to unlock.

**Comment by ncminer** [comment]
Is that the file named nodekey?

**Comment by immartian** [comment]
No it's under /Library/Musicoin/keystore if I'm not wrong.

**Comment by ncminer** [comment]
I have the UTC file in the keystore file

**Comment by ncminer** [comment]
Is this what you mean?

**Comment by immartian** [comment]
then you have the control and can unlock it unless you input wrong password, pls try to trim spaces.

**Comment by ncminer** [comment]
I'm not sure what I did wrong. It's working for one acct but not the other(same pw for both) I'll keep trying.

Thank you very much for taking care of the wallet update issue so quickly.

**Comment by ncminer** [comment]
I got it. I'm getting old. Sometimes my 2 and Z look alike.   Thanks again to both you and @Varunram for your help.
