### ISSUE TITLE
How to add private key to my wallet app?

### ISSUE THREAD

**Issue by taismi** [Musicoin/desktop#45]
I have my public key and private key. How to add my private key to my wallet app?

If I click "Add existing account" wallet app ask only my public address and send option is not available. I don't have a UTC file only public and private address.

**Comment by aramikg** [comment]
Having the same issue here, Added my account  - it shows my balance but can't send from it?

**Comment by ihinojal** [comment]
I also had this problem. This is not documented anywhere I could find.

What I've done is generate the UTC file using MyEtherWallet chrome extension (web version is not enough). Once you add the MUSIC private key, and add a password go to "MyWallets". Will show 0 as balance as is connected to the ETH network, it doesn't matter. Tthen the option to download JSON/UTC file will be visible. Download the file and drop it in the folder that musicoin-wallet is expected to find it.

If any of you guys keep having doubts just tell me something.

**Comment by musasimsek** [comment]
I do this and my musicoins go to the hell, You must think twice before do this!!!!

**Comment by ihinojal** [comment]
Can you elaborate your problem? I don't have musicoin anymore but maybe I
can help you if you describe the issue

**Comment by immartian** [comment]
@cryptofuture maybe we should address this issue in next version.

**Comment by cryptofuture** [comment]
I'm looking into it now, and looks like its more critical as it sounds in an issue. User is not only not able to import key with private key, but not able to even to import with JSON/UTC file. Basically is just dump dialog, and there no possibility to import at all now, without manually copying files.
