### ISSUE TITLE
v0.70 vs v0.7.0

### ISSUE THREAD

**Issue by igotfits1** [Musicoin/desktop#46]
just a small type in the wallet, before you open the wallet you have v0.7 up top. once in the wallet it's listed as v0.70

wallet fills up screen when open, which i believe is the first wallet ive used that does that, when minimizing to a smaller size buttons overlap eachother in the wallet.

other then that wallet looks and works flawlessly.

**Comment by Varunram** [comment]
Thanks! We'll fix this in upcoming releases.
