### ISSUE TITLE
Can't sync the wallet

### ISSUE THREAD

**Issue by xgene34** [Musicoin/desktop#49]
Hi,

last 10 days it's not possible to sync the wallet.

Tried adding also nodes manually but it doesn't help.

Still not connecting to peers.

Any solution from u guys? I'm using desktop wallet on IOS.

Thanks

**Comment by immartian** [comment]
Can you post a screen shot? Did you run some other Wallet at the same time?

**Comment by xgene34** [comment]
Hi,

Sometimes I had exodus on but most of the time no other wallet is running.
Sure here it is:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/13034039/31237561-9bffc26c-a9f7-11e7-9d65-53123ee303db.png">

And now it stays like that for hours.

I also tried opening wallet before sync and adding nodes myself that I found here but still no luck.

But it worked fine before that. Last 10 days nothing!

**Comment by immartian** [comment]
can't see you picture. Are you running on Windows/Mac/Linux?

**Comment by xgene34** [comment]
on Mac

**Comment by xgene34** [comment]
here is a bigger picture:

![image](https://user-images.githubusercontent.com/13034039/31263229-2a46ab44-aa61-11e7-9f60-59e1de8df0e6.png)

**Comment by immartian** [comment]
Did you try to add some peers from this list? 
https://github.com/Musicoin/desktop/blob/master/bootnodes.json

**Comment by xgene34** [comment]
yes. I get message "Connecting17peers along with default remore Nodes" but none get connected to sync

**Comment by immartian** [comment]
can you show a screen of add peers window?

**Comment by xgene34** [comment]
sure...
![image](https://user-images.githubusercontent.com/13034039/31263606-98b5b6c2-aa63-11e7-98fd-cd18ec745765.png)

I tried with/without quatations, adding the lines as shown in file...nothing helped

**Comment by immartian** [comment]
Just follow the format, without quote. 
Also pls check if you other wallets running at the same time.

**Comment by immartian** [comment]
Since it's not supporting channel in github, pls go to support channel at slack.musicoin.org. close for now.
