### ISSUE TITLE
Popup dialog showing "Your preference can not be read"

### ISSUE THREAD

**Issue by immartian** [Musicoin/desktop#5]
On #Linux:
> ./Musicoin-client 

The main program window showing correctly now, but there's always a floating dialog like this: 

![image](https://cloud.githubusercontent.com/assets/81030/20270419/eef5b12e-aac1-11e6-9ca9-dc0b2aa6d08e.png)

It can be closed without violating the normal functions, but annoying.

**Comment by phiferd** [comment]
This is definitely coming from some chrome/nwjs library.  

https://ubuntuforums.org/showthread.php?t=1499189

It looks like nwjs creates a folder in the .config directory just like chrome does.  So, based on the advice in the article above, try this:

`rm -rf ~/.config/Musicoin-client`
