### ISSUE TITLE
Wallet wont sync peers are added

### ISSUE THREAD

**Issue by ghost** [Musicoin/desktop#52]
I have added all node peers and wallet has been open for 2 days. but will not sync i have disabled firewall also antivirus uninstalled walled reinstalled. still getting nowhere any suggestions

**Comment by Varunram** [comment]
@Thomasmcdaniel9 IS any other wallet running on your system? Could you provide us with the Operating System specifications?

**Comment by Thomasmcdaniel9** [comment]
No other wallets. Running.  Ruining windows 7 pro

**Comment by 776977** [comment]
Same issue. No sync after UBI. Window 10 pro.

**Comment by Pilotvt** [comment]
same. I tryed ver.7 and 6. Both are getting stuck

**Comment by saifer6666** [comment]
Me too. WTF is going on ?

**Comment by mc-andre** [comment]
If you cannot sync under win10, try deleting the "chaindata" folder located in c:\user...\appdata\roaming\musicoin, and create the folder "chaindata" again where the original was, it should start downloading.

**Comment by madpc44** [comment]
I have an issue with my Musicoin wallet V0.70 in that the Balance is not updating. 
I backed up the chain data folder and deleted as suggested as above then re-run the wallet only to see my Balance reset to zero :-/. fortunately I was able to copy the chaindata folder back and restore my balance but it is still not updating.

**Comment by syedmeesamali** [comment]
I am also having issues with Syncing. Been Syncing for over 12 hours and still NO PEERS found. What is the reason and solution? My OS is Windows 10 Home edition.

**Comment by OCSHAUN** [comment]
Same problem here... Im assuming I should get a wallet elsewhere?

**Comment by robertbuerger** [comment]
Hi there,
I'm having the same problem. I've deleted the chain data, added peers but 0.7 is not even connecting to at least 1 peer. So I've tried 0.5 and its downloading the chain until block 1,547,718. From here it does not move forward. "Last block 6h" but 6 Peers connected.
I've tried this 3 times. Always stopping at block 1,547.718.

I'm looking forward to your help.
Thx

**Comment by Varunram** [comment]
New wallet is due to release. Please checkout the beta over at https://forum.musicoin.org/topic/144/musicoin-wallet-v0-8-testing.
