### ISSUE TITLE
Cant move Wallet Data to another drive (out of space)

### ISSUE THREAD

**Issue by delonbh** [Musicoin/desktop#53]
How can I move "%appdata%\Musicoin" to another drive and execute it from there?

Thank you.

**Comment by wally-70** [comment]
Hi,

Here you have the procedure step-by-step. Is very easy.

1. If the wallet is open, close it.
2. Make **A COPY** of your original folder from C:\Users\[username]\AppData\Roaming\Musicoin to your desired new location.
3. **Rename** the original folder (to "Musicoin old" for example) for backup purposes. It's better to prevent than to cure.
4. Open a Command Prompt window (cmd) **with administrator rights**
5. Make a symbolic link to the new folder by typing
	`mklink /d [full old path] [full new path]`
6. You will receive the answer: `symbolic link created for [old path] <<===>> [new path]`
7. Open Musicoin Wallet and synchronize it to ensure that all things are working and wallets are in place.
8. Delete the original folder

Done!
And ALLWAYS have a backup of your wallets from \Musicoin\keystore to other place to avoid lose your cryptos if something goes wrong with your PC!!!

Hope it helped you!

**Comment by delonbh** [comment]
thank you ver much

Em 21/10/2017 18:55, "wally-70" <notifications@github.com> escreveu:

**Comment by Varunram** [comment]
Closing this since it has been solved.
