### ISSUE TITLE
Can´t move my musicoin from walleten, have no send button.

### ISSUE THREAD

**Issue by Femtes** [Musicoin/desktop#60]
My computer crashed and unfortunately i didn´t have any backup for the wallet when it was on the disc that was lost. Everything else I have saved, but now I will move my coin and of course no send button show up. Adding existing account but no send button pops up. How do I fix it?

**Comment by Varunram** [comment]
If you didn't have a backup for the wallet (the UTC file along with its password), there's no way you can get back your coins. The data you have saved will be regarding the blocks itself, which can be got back anytime by res-syncing the blockchain.
