### ISSUE TITLE
music coin v0.5 wallet not synchronize on mac oc sierra. 

### ISSUE THREAD

**Issue by Alex3444** [Musicoin/desktop#63]
Hello, The musicoin wallet v0.5  for MAC OC Sierra  is not syncing anymore. I leave it on all 3 days but it does not synchronize.
The balance in musicoin orbiter is correct,  but in the wallet the balance does not appear correctly.
Please help me with this issue.

**Comment by Alex3444** [comment]
<img width="998" alt="2017-12-11 10 16 38" src="https://user-images.githubusercontent.com/34439546/33826303-75d468ec-de5c-11e7-9c87-c4e58feaaca3.png">

**Comment by immartian** [comment]
try new version 0.7.

**Comment by Alex3444** [comment]
<img width="830" alt="2017-12-11 11 37 09" src="https://user-images.githubusercontent.com/34439546/33829319-ae69e1fe-de67-11e7-834b-75fe86400244.png">


same problem :(

**Comment by Varunram** [comment]
Your block number indicates that you're many blocks away from the current block. Please wait till the sync completes and you'll be able to see your coins.

**Comment by Alex3444** [comment]
but how long I have to wait ?
<img width="830" alt="2017-12-11 13 10 29" src="https://user-images.githubusercontent.com/34439546/33832609-b378db48-de74-11e7-94c1-c752013bff38.png">

**Comment by Alex3444** [comment]
in 2h time its nothing change :(

**Comment by Varunram** [comment]
Click open wallet before sync is complete and you can see the block at which the sync is at currently.

**Comment by Alex3444** [comment]
<img width="1209" alt="2017-12-11 13 25 06" src="https://user-images.githubusercontent.com/34439546/33833190-cb738778-de76-11e7-8e58-9eacebfcfcd7.png">

**Comment by Alex3444** [comment]
so I just have to wait or my be there is some other option to avoid huge amount of waiting time?
