### ISSUE TITLE
Move current block info to a more prominent position

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#67]
The present block info and syncing info should ideally find their place in the first page, without the user having to click through. A more prominent placement is also desired.

**Comment by idontcar3** [comment]
Hello, I'd like to be the one who resolves this issue and help you guys keep growing.

**Comment by Varunram** [comment]
Thanks @idontcar3. Assigning the issue to you.

**Comment by Varunram** [comment]
Closed via https://github.com/Musicoin/desktop/commit/14d87f8ca8440fe67ceece6510748740d2ec2999
