### ISSUE TITLE
Inform % of  blocks synced

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#68]
On the first page, it would be nice to show a percentage of the blocks being synced, so that people wouldn't have to wait indefinitely. The way this would work is, on startup, get the tip block from orbiter, get the current block synced locally and continuously update the percentage. Accuracy to one decimal place is enough, but more are welcome anyway.

EDIT: The info is in the second page, so the first step is to move it to the first page, get rid of the loading bar on the first page, have a nice modal in a 123/12345 format with percentage in small letters at the bottom.

**Comment by idontcar3** [comment]
Hello, as always i want to contribute with you guys and now time allows it.
I'd like to be the one who resolves this issue in the next 24hrs if The Force and the internet allows it.

Already sketched something for you guys.
