### ISSUE TITLE
Have light/dark themes

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#70]
We could shift into a lighter theme overall taking inspiration from <a href="https://github.com/ethereum/mist/releases/"> Mist </a>. This would involve a fair amount of work and should ideally be along with #68 to prevent conflicts later on.

**Comment by adrianhartanto0** [comment]
Hey! I would like to work on this issue. I am also thinking there should be a switch to toggle between dark and light theme

**Comment by Varunram** [comment]
@adrianhartanto0 Sure, feel free to start working and contact us if you'd like help or assistance.

**Comment by Varunram** [comment]
@adrianhartanto0 Some quick stuff regarding what we'd expect:
1. Please remove the pictures in the background which are there right now and replace them with a more suitable background.
2. The dark theme should have suitable colours, right now, visibility is really poor (headings highlighted in bold, fonts based on os, etc.)
3. The light theme must change the background and the text. It shouldn't affect the positions of other elements.
4. The toggle switch can be made on the first page instead of the second one, so that its easier for people to shift towards the same.

**Comment by Varunram** [comment]
@adrianhartanto0 Can you open a PR so that we can comment on the changes? Thanks!

**Comment by Varunram** [comment]
Bounty reduced since part of the changes were made by @cryptofuture in his latest PR.

**Comment by movingelectrons** [comment]
I assume this still needs to be done?  Seems like this would be great for me, get acquainted with the code a bit and actually do something useful at the same time.

**Comment by etaletai13** [comment]
@movingelectrons It's being worked on, but needs more contributions and is probably for the best to be collaborative I think! I'm in, too.

**Comment by Varunram** [comment]
Upgraded bounty to 10k MUSIC.

**Comment by etaletai13** [comment]
Well that's a nice bounty.

**Comment by movingelectrons** [comment]
@etaletai13 collaboration would be great, I have quite a bit of experience with css3, but I am lacking in experience when it comes to the frameworks being used now, bower, wm, and all the likes are very new to me, when I had the code base working a month or so ago, I was going to try and make a button to switch the css, but I failed to get anything to work.. I mean I could change the colors and whatnot easily with the css I eventually found, but as far as making a 'button' or any kind of functional menu item goes.... :( I did notice there where some kind of themeing templates or something like that in place, but I could not find any documentation whatsoever on the net.

Does anyone know of any demos, guides, or tutorials showing the basics of the frameworks being used here?  When I was new to RoR, there was a plethora of them, very easy to get started!  I am hoping there are some equivalent things for at least a few of the things being used here... last RoR app I wrote (onetotheworld.com) and actually also the ones before that, I had gotten into the habit of writing tests using shoulda, I tried using rspec but found shoulda and friends much easier to use.  So I hope to help in that department as well.  First I need to get the current codebase working though.. I am stuck on 'yarn' : says "ERROR: There are no scenarios; must have at least one."  Trying to follow along with the yarn docs, but I can't seem to get past even this $ yarn init
ERROR: [Errno 2] No such file or directory: 'init'

I am beginning to thing I do not even have yarn installed correctly, $ yarn --version
0.27
is that even correct?

**Comment by etaletai13** [comment]
I would like to ask everyone to post with whatever kind of changes to the ux module you would like for ease of design; no need for designers to code or vise-versa. I use yarn for what I call 'crochet', using hooks and linting and passing strings through ... you get the idea. So let's get a scaffold going that even people working on eth will want.

**Comment by movingelectrons** [comment]
@etaletai13 re: fork https://github.com/etaletai13/ux forgive me if this is a dumb/basic question, but how do I go about viewing my changes? I tried opening index.html in chrome, as well as trying a few yarn incantations, but no luck so far

**Comment by etaletai13** [comment]
@movingelectrons You'll have to test in the app, by changing the location of the ux module to your own, so that it will pull into the new build/test.

**Comment by Varunram** [comment]
I think we can close this since this was claimed in https://github.com/Musicoin/desktop-interface/pull/13
