### ISSUE TITLE
Improve Peer Discovery and Config options

### ISSUE THREAD

**Issue by Varunram** [Musicoin/desktop#71]
Peer discovery has always been an issue with the Wallet. Any implementation which seeks to improve our peer discovery is welcome. Preferably along with benchmarks/tests, so that its easier to observe the changes. This would ideally be a big task involving lots of review and updates, so before taking this one up, please comment over here so that we may assign you (a team/individual) towards this.

**Comment by cryptofuture** [comment]
I never had problem with peer discovery, in fact discovery worked always even faster comparing with UBQ network for me. Any thoughts why it happens for some people? Even on bittrex $MUSIC is the wallet with the most amount of peers.

**Comment by Varunram** [comment]
@cryptofuture Thanks for the PR. Here is a non-comprehensive list of the things that I'd like for this PR:

1. Have a separate window/tab (a window on the navbar like Settings > Adjust settings or something. Screenshot attached.

2. In the settings tab, have common CLI options like `cache` and `--fast` which can be passed to the gmc node.

3. Have a config file where the user can save preferences manually. In case the user changes values on the GUI, the values in the GUI take preference over the config file (but must not be overwritten).

4. On first startup, search for peers. After the user connects to a peer, store the peer's info in `bootnodes.json` and connect to these nodes with higher priority the next time the user uses the wallet.

5. If on next startup, the requested peer is not available, it is to be deleted from the list of bootnodes.

6. Finally, if the peer is not syncing, it would be nice if you could change the background to something different (lookout for the changes on #70).

Note: If the desired changes can't be done in `node-webkit`, please checkout <a href="https://github.com/ethereum/mist">the Ethereum Mist Wallet </a> (its in Electron). If you plan to rewrite the app in Electron, bounty will change accordingly. (Both Electron and webkit are equally preferable). The client must be easy to tinker with, but you'd have to change the network parameters accordingly.

Feel free to ask your questions/concerns regarding the above changes and your plan of action.

**Comment by cryptofuture** [comment]
> Have a separate window/tab (a window on the navbar like Settings > Adjust settings or something. Screenshot attached.
You forgot to add attachment
> In the settings tab, have common CLI options like cache and --fast which can be passed to the gmc node.
Fast is default, I first included it, but documentation says that is default in last geth versions. What about gmc? More above is sync was stopped it will be not fast, through is started as fast.
>Finally, if the peer is not syncing, it would be nice if you could change the background to something different
I could change background picture but someone who would make #70 might be need to change picture to more appropriate picture. I'm no an artist.

**Comment by Varunram** [comment]
Just added the picture. Regarding #70, I agree, so you might want to wait so that you could rebase after that. 

> Fast is default, I first included it, but documentation says that is default in last geth versions. What about gmc? More above is sync was stopped it will be not fast, through is started as fast.

gmc is synced with upstream geth now, but the current wallet version has an old one. We will be integrating the latest version with the upcoming release. General setting as a separate window (in the navbar) should be enough

**Comment by Varunram** [comment]
Since the changes to the window have been finalised, I think having some text "Config Options" on the first page, which when clicked opens a modal with the various options should be enough. Since the change is simpler, I shall reduce the bounty to reflect the same.

**Comment by Varunram** [comment]
Closed via https://github.com/Musicoin/desktop/commit/5c6499a814055ddc163a08525256eb9be8b0f5f2
