### ISSUE TITLE
Building Issue

### ISSUE THREAD

**Issue by adrianhartanto0** [Musicoin/desktop#72]
I wanted to contribute to this project but encountered a problem when building from src, specifically the application is stuck as shown in the image below.

![ss](https://user-images.githubusercontent.com/11606323/33998412-5ef787c6-e122-11e7-953b-7a8a98341d8f.png)

**My specs are:**

OS: Xubuntu Xenial
node version: 9.3.0
ipfs 0.4.13: running on localhost:8080

**My Commands are:**

./gmc-linux-amd64 --fast --cache=512 --rpc --rpcapi="db,eth,net,web3,personal" --rpcport "8545" --rpcaddr "127.0.0.1" --rpccorsdomain "localhost"

After Fast sync complete:

ipfs daemon -> nw

**Note:** 
1.) I downloaded the `nw` SDK and create a symlink from in `usr/bin`. Not sure if it is correct
2.) I ran install.sh for ipfs

Any help is appreciated!

**Comment by Varunram** [comment]
Hey, thanks for contributing to the repo. Quick questions - did you download the wallet in the first place? If so, after downloading, did you run `npm install` on that?

**Comment by adrianhartanto0** [comment]
I managed to get the application to show up (as shown in the image below). Is there a way to check if it's running in the way that it should? 

I saw an error in the terminal that says `Failed to start child process Musicoin Wallet: Error: spawn ./gmc ENOENT`.  Should I be worried about anything?

![ss1](https://user-images.githubusercontent.com/11606323/34044330-832da1e4-e1df-11e7-9a19-cd25a1335b11.png)

**Comment by idontcar3** [comment]
@adrianhartanto0 the issue lies in the file `config/config.std.js`

it is prepared to start gmc (Go-Musicoin chain) from the prepared directory.
make sure to see the [server_setup.sh script](https://github.com/Musicoin/desktop/blob/master/server_setup.sh) which points out how it has to be routes for gmc binary.

May the force be with you.

**Comment by Varunram** [comment]
Closing this due to lack of response. Please reopen if you face the same issue.
