### ISSUE TITLE
Walk a noob through setting up v.7 of the musicoin app

### ISSUE THREAD

**Issue by musicNoob** [Musicoin/desktop#76]
I havent used musicoin desktop wallet in a while so when I opened it, I found I needed an update. I downloaded the newest version, but right now, it wont sync at all. After reading through the README file and things on here, it seems like I might need to take some additional steps to get this to run properly. Am I missing something? Do I need to do something OTHER than just double click the desktop icon to get this to run properly? Is there something that needs to run in the background or anything? The previous version ran fine, so I'm not sure if this new version is different or why I cant sync or find peers. Help a noob out! Haha thanks

**Comment by mc-andre** [comment]
Make sure you have large enough disk space for downloading our blockchain. And don't run other ethereum related wallet software in the background. Set up the time on your device as it could be one of the problem why your wallet won't sync in real time.

**Comment by ruzanoff** [comment]
All done. Added 120 peers. But none was found (0-1 peers). Maybe there is a updated list of peers? Three days can not use the wallet.
P.S. The port is free, no antivirus, Windows 7x64, wallet 0.70

**Comment by musicNoob** [comment]
I took a spare laptop I had laying around and installed the software on there and was able to sync. Im not sure why I cant sync on my main PC still. Im not sure if the gmc is being blocked somehow, but I allowed it past any firewalls I had up. But anyway, now that its up, I DID backup my wallet info -- how do I transfer that to my laptop? Thank you for the help!

**Comment by mc-andre** [comment]
Locate the backup file named "UTC--20xx-xx-xxxxx-xx-xx" in the "keystore" folder. Then in a new device, create a new "keystore" folder manually and put the backup file inside. I would recommend saving that keystore file and the password somewhere safe, since you will need those to retrieve your wallet.

**Comment by musicNoob** [comment]
Bingo!! We're up and running! Thanks a bunch!

**Comment by Varunram** [comment]
Closing this since it has been resolved. Thanks @mc-andre!
