### ISSUE TITLE
Wallet 0.7 wont sync..

### ISSUE THREAD

**Issue by raylusion** [Musicoin/desktop#78]
ive been minning on musicoin pool directly i have 20 shares. erased and created new chaindata file and nothing.. still have my cools in pool.. any other wallet i can send it out too? windows 10 pro no other wallet, jaxx but i dont open.

**Comment by Varunram** [comment]
@raylusion We're going to release a new version of the wallet within the next two days, could you see if using that makes things better? Thanks!

Regarding the wallet not syncing, I have a few suggestions: Check whether your system time is synced properly and whether you're running any other ETH like wallets. This is the number one cause that wallets don't sync.

**Comment by carlo0000** [comment]
is the new wallet released ?
my wallet is also not sync it s 20 days behind  sometime i see peers but most of the time no peers
and also why is the wallet so empty ?  it could at lease show the historic transactions

**Comment by Varunram** [comment]
New wallet v0.8 is in beta and can be found over at https://forum.musicoin.org/topic/144/musicoin-wallet-v0-8-testing.
