### ISSUE TITLE
Musicoin stuck at 1500000 blocks

### ISSUE THREAD

**Issue by mathias7799** [Musicoin/desktop#79]
http://prntscr.com/hr4ea0 it has been stuck at 1.5M blocks for a few days now...

**Comment by mathias7799** [comment]
And my system time is set correctly, and i don't have any ether like wallets open at the same time.

**Comment by Varunram** [comment]
Hey, is it any better now? Can you check the logs?

**Comment by mathias7799** [comment]
I found out the problem so nvm.. lol

**Comment by idontcar3** [comment]
please @mathias7799 could you tell us how did you managed to resolve this issue?.

Sometimes is something silly and we get that, but evne the silliest thing can help another person save some hours of debugging.

**Comment by mathias7799** [comment]
@idontcar3 So, i downloaded the other wallet parity and it found the peers that i needed for the download.

**Comment by Varunram** [comment]
Since this has been resolved, closing this for now.
