### ISSUE TITLE
Fixed 0.7 Wallet This is what I Did

### ISSUE THREAD

**Issue by raylusion** [Musicoin/desktop#80]
Step 1. Delete Blockhain folder (Under Key Backup in Musicoin wallet)
2. create blockchain folder, once you delete old one.
3. download time synchronization, update time, for windows 10 pro users i had to begin with 0.7 and during half way i download 0.5 and it synced very fast after that, is my musicoin wallet in coins or usd value?
Bounty  0x22e392b3b2889c16cfc1109d1ec2128ca5783f5e

**Comment by Varunram** [comment]
I'm assuming that the steps you followed fixed the issue you had. If you could explain a bit more as to what you're facing, we could help you.
