### ISSUE TITLE
4,706.06 on my musicoin wallet balance

### ISSUE THREAD

**Issue by raylusion** [Musicoin/desktop#81]
is this how many coins i have? or this means something else? im asking becuase i only mined 3 days with 1  rx 580 8gb.. so im a little excited if true.

**Comment by mathias7799** [comment]
I would think so, please send screenshots.

**Comment by raylusion** [comment]
https://www.reddit.com/r/musicoin/comments/7lxurp/i_have_21k_coins_in_3_days_with_1_gpu_and_cant/

**Comment by immartian** [comment]
can you post your screenshot on which block number you are currently synced? let's make sure you are mining the same blockchain.

**Comment by raylusion** [comment]
1.509.159

**Comment by immartian** [comment]
1. the top block now on chain is 1,69x,xxx  https://explorer.musicoin.org/
2. you probably didn't mine Musicoin at at, although it could be validated
once you sync up totally to the top height

**Comment by immartian** [comment]
1. the top block now on chain is 1,69x,xxx  https://explorer.musicoin.org/ 
2. you probably didn't mine Musicoin at at, although it could be validated once you sync up totally to the top height

**Comment by raylusion** [comment]
I didn't mine anything else 😔

**Comment by immartian** [comment]
what's your address of miner wallet? you can check explorer.musicoin.org to validate it's really mined.

**Comment by Varunram** [comment]
@raylusion Any updates on this thread?

**Comment by Varunram** [comment]
This due to inactivity. Please open a new issue if you face this again.
