### ISSUE TITLE
Can't transfer any musicoin to anywhere.

### ISSUE THREAD

**Issue by s1nang** [Musicoin/desktop#82]
Well I'm noob on coin world and musicoin. 

I've made an artist page, and it's verified: https://musicoin.org/nav/artist/0x0270e717fd7e12b9fa7eb0f19cb197fb27981918

Got some listenings and just wanted to transfer my musicoins to somewhere else to just to check how the system works. 

I got **cryptopia** account (**bittrex** is closed to sign ups) and also got desktop wallet (v0.5). But no success to send any coin between **profile wallet ---- cyrptopia balance --- desktop wallet**. So I'm stuck and got really bored of this as I guess this is the simplest action in coin world, right? Just copy paste the address and push send...

I really wonder what I'm missing.

I synced desktop wallet (took 3 hours, but now it syncs faster) and also got mining on, but it mines extremely high amount of musicoins like 8-10K per hour (i guess these are not real musicoins, otherwise I'm earning tons of dollars lol)

I fixed the system clock, disabled ad-blocker (nothing change)

I'm using hackintosh system but I also have a macbook pro, I did everything on macbook pro too, no chance!..

BTW I could manage to transfer $MUSIC to my friend's Bittrex address, that's the only success I experienced during last week lol.

So what's my problem, will I die? Thanks!

**Comment by Varunram** [comment]
You can transfer coins from your web wallet on musicoin.org to a desktop wallet, sending them to an exchange would not work since exchanges don't support that (and this is indicated in the profile section above the send button). You can transfer coins from an exchange to your web wallet though, that should work fine. Regarding Desktop wallet, I think you must be mining some other coin because the option to mine musicoin is disabled in v0.7 of the wallet. You should not have any other  Ethereum like wallets running in the background, since we use the same port and an another oft-cited reason is the failure to sync system time.

**Comment by raylusion** [comment]
i have 22k in 3 days, knew something was not right... cant send to cryptopia neither... how come so many coins in so little time, i have only 1 rx 580 8gb and 21k in 3 days? knew it was too good to be true..

**Comment by raylusion** [comment]
Waiting for transaction 0x470ab2744ae909ecfb1bad512cc812a2890a6f10c3606df26d9aea6a69e2fb1b

**Comment by s1nang** [comment]
I installed v0.7 wallet and tried to sync on both of my computers, hackintosh and macbook pro and went to sleep. At morning now, they are still not synced and no progression on loading bar. Free spaces > 60gb, clocks synced, no firewall.

I guess I'm going to wait for the new wallet:) well I support your work with my heart, you are doing great, I'm pretty sure everything gonna be perfect when non-beta version of the site has been published. Cheers!

**Comment by mountainSanchez** [comment]
ive send some coin to the crytopia....and my web wallet has already deduct the amount....yet crytopia not receive yet...why?

**Comment by raylusion** [comment]
It takes time. But it arrives

**Comment by Varunram** [comment]
@mountainSanchez The if you send coins directly from the web wallet to exchange ignoring the warning, you'd have to contact the exchange regarding the lost coins

**Comment by s1nang** [comment]
Cryptopia has finally messaged me and they say MUSICOIN is under maintenance and no ETA to complete maintenance. You can check here: https://www.cryptopia.co.nz/CoinInfo/?coin=MUSIC&view=links

**Comment by Varunram** [comment]
Closing this since service has resumed normally according to reports.
