### ISSUE TITLE
coin to crytopia

### ISSUE THREAD

**Issue by mountainSanchez** [Musicoin/desktop#83]
ive send some coin to the crytopia....and my web wallet has already deduct the amount....yet crytopia not receive yet...why?

**Comment by immartian** [comment]
did you see this message? 
![image](https://user-images.githubusercontent.com/81030/34349670-79a511c2-ea4d-11e7-8f3d-1b33d8a0fd14.png)

**Comment by mountainSanchez** [comment]
means my coin has been eaten or ????....then what for can i use this music coin

**Comment by immartian** [comment]
please take down your tx number(e.g. https://explorer.musicoin.org/tx/0x14a4dd6510a846f344578336a68dbbea9735255cfc7ea2e746f706be9a37a17a ) and report to Cryptopia support, they will find back your money.

**Comment by mountainSanchez** [comment]
the problem is...my profile doenst show any trasaction at all...it  just disappear
