### ISSUE TITLE
Why send option is not available for wallet address created in musicoin.org account?

### ISSUE THREAD

**Issue by livey0u** [Musicoin/desktop#85]
If I create a new account from desktop wallet, send option is available. But, not when I add an existing account! Could anyone help me understand, why the desktop wallet is done this way?

**Comment by Varunram** [comment]
Are you importing your web wallet into local? The web wallet acts as an exchange i.e. the private keys are not visible, so you would not be able to import the web wallet into the desktop wallet. To transfer coins, please create a local desktop wallet, transfer your coins from the web wallet to the desktop wallet and then to an exchange.

**Comment by livey0u** [comment]
I don't want to use the web wallet for some reasons & also don't want to pay for transferring to my another account. Why not musicoin.org let me to download the private key & allow me to upload the same in desktop wallet?

**Comment by Varunram** [comment]
That's not possible due to security reasons but the gas fee is very cheap, it shouldn't cost you a lot.

**Comment by livey0u** [comment]
It my money. I don't want to spend unless I want to. There are many services & wallets allows user to download private key. I used a few myself. Could you explain, what kind of extra security that musicoin.org provides more than those allows user to download private keys?

**Comment by Varunram** [comment]
Allowing users to download the private key is not permitted by many exchanges, I'm afraid that is a feature which will not be implemented on the website. The gas fee is 0.001MC only, so I don't think there's any problem with that at current rates.

**Comment by livey0u** [comment]
My question is still unanswered!

**Comment by Varunram** [comment]
The issue is "Why send option is not available for wallet address created in musicoin.org account?" and the answer to that is that the send option is available for the wallet address and exporting keys is not a feature we're looking to implement anytime soon. Please contact support if you'd like to enable that as a feature.
