### ISSUE TITLE
Sent coins to cryptopia and they did not arrive

### ISSUE THREAD

**Issue by maevin** [Musicoin/desktop#87]
how do I check what was sent and when. I have sent coins twice before without a problem

**Comment by Varunram** [comment]
@maevin Cryptopia is facing a few issues with their Musicoin wallet, it would be better to contact them directly about it.

**Comment by maevin** [comment]
Ok thanks. Is there a way to get a copy of my transactions

**Comment by Varunram** [comment]
I think Cryptopia should have the transaction ids of all outgoing transactions. Please contact cryptopia through their official channels if they aren't present.

**Comment by maevin** [comment]
ok but I need my outgoing as I sent them

**Comment by maevin** [comment]
https://orbiter.musicoin.org
This seems to be where

**Comment by maevin** [comment]
https://explorer.musicoin.org/
This is better

**Comment by Varunram** [comment]
@maevin Yeah, explorer is our latest blockchain explorer and should work at all times. Orbiter was reported to have a few bugs, so we decided it would be better to spin up a new explorer based on Parity.
