### ISSUE TITLE
Self-listening and self-tipping issue

### ISSUE THREAD

**Issue by musicoj** [Musicoin/desktop#9]
I'm not sure if it's an issue but in theory I can use just 10 coins to make a lot of rounds of listening and tipping to my own works then create fake rankings. Of course the gas cost and duration of each payment can be less like an attack, but seems also like a malicious action.

**Comment by phiferd** [comment]
Yes, I'm not too worried about that in the long-term.  Once we have enough users it will need difficult to have much impact.  It's easy to mitigate, but you could imagine two users both typing each other, and we are right back to the same issue.

**Comment by musicoj** [comment]
yes, it'd be much difficult to impact to millions. if it's not programming to fake so.
