### ISSUE TITLE
Please don't accept pull requests with node_modules folder

### ISSUE THREAD

**Issue by cryptofuture** [Musicoin/desktop#90]
Subj.
```
Miscellaneous Warning EINTEGRITY: sha512-/UETyP0W22QILqS+6HowevwhEFJ3MBJnwTf75Qob9Wz9t0DPuisL8kW8YZMK62dHAKE1c1p+gY1TtOLY+USEHA== integrity checksum failed when using sha512: wanted sha512-/UETyP0W22QILqS+6HowevwhEFJ3MBJnwTf75Qob9Wz9t0DPuisL8kW8YZMK62dHAKE1c1p+gY1TtOLY+USEHA== but got sha1-NA3tvmKQGHFRweodd3o0SJNd+EY=. (13730 bytes)
```
We must add it to gitignore. Beside it bad for security, and it shouldn't be in the codebase.

**Comment by cryptofuture** [comment]
Is already in gitignore, idk what shady software @idontcar3 use, but please just don't do it again.

**Comment by Varunram** [comment]
Thanks, right now only secp256k1 is in the node_modules folder, which will be removed in the next release.

**Comment by cryptofuture** [comment]
Yes, will be good not to have node_modules folder at all.
