### ISSUE TITLE
how to run wallet with parameters or config at windows

### ISSUE THREAD

**Issue by bozgoren** [Musicoin/desktop#98]
Hello,

I download and run windows wallet but nothing happening. I download gmc for windows run it with some parameters and its synchronising now.

So now i need to run that windows wallet coordinating with gmc i am running. With a parameter or config file may be?

I dont want wallet launch gmc background where i cannot see what is happening. especially at the start, when it is not launching, or having some problem.

**Comment by Varunram** [comment]
This option has been aded in an upcoming release of the wallet (wallet v1.0). Stay tuned!
