### ISSUE TITLE
Desktop Musicoin wallet not syncing

### ISSUE THREAD

**Issue by ajjensson** [Musicoin/desktop#99]
Hi everyone,

Please forgive the newbie questions but, is my desktop wallet the only place where my coins are stored? I have a few rigs mining musicoin and the pools show the balance paid, but I am not sure how to access these paidout coins with my wallet. 

Also, the Desktop (win10 64-bit) wallet is not syncing , despite finding peers and beginning to download. Need some halp please!

:)

**Comment by Varunram** [comment]
@ajjensson could you try desktop wallet 0.8beta specified over at forum.musicoin.org? Thanks!

**Comment by matjazwinkler** [comment]
Hello, I want to transfer Musicoin from Bittrex to Cryptopia... I understand I need to transfer from Bittrex to "personal" wallet first and after that from "personal" to Cryptopia.
I managet to get an wallet in "Musicoin -wallet 0.7 for MAC". I sent from Bittrex to the address in the wallet... but after 1,5h still balance is 0 ... 
What can I do? 
Did anyone successfully transfer funds from "personal" wallet to Cryptopia today?
Thanks

**Comment by NewtonSys** [comment]
i made a direct transfer from bittrex to cryptopia since 9 hours.. still nothing.. although the transaction shows in the blockexplorer.. on cryptopia the wallet is fine, but connections to nodes are 0.. i dont know what happened to my money now!

**Comment by Varunram** [comment]
Cryptopia is currently off-line and they aren't responding to our support emails. Please contact Cryptopia support so that they can help you out. We are working with other exchanges to get Musicoin listed, so that choice isn't limited.

**Comment by Varunram** [comment]
Closing this since service has resumed normally.
